/* IGNITE event delegation layer. DOM intent is translated into feature actions here. */
export function initEvents(ctx){
  const {state,load,save,clearAllTopicStorageOnce,createRouter,initEvents,app,esc,resetViewport,exportAppBackup,restoreAppBackup,resetAllAppData,syncModeTheme,journeys,readBond,writeBond,pickBond,TOPIC_MANAGER_KEYS,ROLE_KEYS,readContent,saveContent,cleanRole,getTopicStats,contentStats,contentTotal,initMechanic,mechanicAction,mechanicView,winnerLabel,isMechanicComplete,resetMechanic,renderMinigameMenu,minigameView,minigameAction,openMinigame,getProgress,getLevelInfo,progressionStartJourney,completeJourney,completeActivity,completeRitual,recordMinigamePlayed,achievementList,starterTruth,starterDare,renderMemorySummary,renderMemories,renderPreferences,renderFeatureSettings,handleVibeClick,handlePreferenceSubmit,surpriseContext,dynamicContext,renderContextSummary,handleMoodClick,saveMemory,getMemory,updateMemory,deleteMemory,toggleMemoryFavorite,recordVibe,recordInteraction,getPreferences,recordMemorySaved,recordOneMore,initAccessibility,coupleName,setView,render,renderBottomNav,renderJourneyGenerating,renderWelcome,renderVibeSelector,daysTogether,nextAnniversary,tonightSuggestion,homeModalOverlay,renderHome,renderBond,renderNames,renderIntro,renderMechanic,renderSession,renderMemoryCapture,renderComplete,renderMinigames,formatJourneyDate,renderJourney,renderJourneyDetail,profilePhoto,renderProfile,renderSettings,renderTopics,importContentSource,resetJourneyMechanics,setMode,generateJourney,startJourney,begin,next,skip,exitSession,restart,saveNames}=ctx;
app.addEventListener("input",function(e){if(!e.target?.matches("input[name=steps]"))return;const value=Math.max(3,Math.min(12,Number(e.target.value)||5));e.target.value=String(value);e.target.setAttribute("aria-valuenow",String(value));e.target.setAttribute("aria-valuetext",value+" steps");const out=document.querySelector("#journey-steps-value");if(out)out.textContent=String(value)});
app.addEventListener("change",function(e){if(e.target?.id==="topic-source-import"){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{importContentSource(JSON.parse(reader.result))}catch{alert("Invalid source JSON.")}};reader.readAsText(file);return}if(e.target?.id==="app-backup-import"){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{restoreAppBackup(JSON.parse(reader.result))}catch(err){alert(err?.message||"Invalid IGNITE backup.")}};reader.readAsText(file)}});
app.addEventListener("click",function(e){
 const ha=e.target.closest("[data-home-action]");if(ha){if(ha.dataset.homeAction==="profile")setView("profile");return}
 const hq=e.target.closest("[data-home-quick]");if(hq){if(hq.dataset.homeQuick==="memory")setView("memory-capture");else if(hq.dataset.homeQuick==="play"){state.__minigameActive=null;setView("minigames")}return}
 const hm=e.target.closest("[data-home-modal]");
 if(hm){state.__homeModal=hm.dataset.homeModal;render();return}
 const hma=e.target.closest("[data-home-modal-action]");
 if(hma){const action=hma.dataset.homeModalAction;
  if(action==="close"){delete state.__homeModal;render();return}
  if(action==="start-moment"){delete state.__homeModal;startJourney(state.mode==="dark"?"dark":"normal");return}
  if(action==="surprise-start"){delete state.__homeModal;const ctx=surpriseContext(getLevelInfo(getProgress().xp).level);startJourney(ctx.journeyId,{targetSteps:ctx.targetSteps,bias:ctx.bias});return}
  if(action==="quote-new"){render();return}
  if(action==="message-copy"||action==="message-share"){const text=document.querySelector("#quick-message")?.value?.trim()||"Thinking about you ♥";if(action==="message-copy")navigator.clipboard?.writeText(text).catch(()=>{});else if(navigator.share)navigator.share({title:"IGNITE",text}).catch(()=>{});else navigator.clipboard?.writeText(text).catch(()=>{});return}
 }
 const hg=e.target.closest("[data-home-goal]");if(hg){const s=readBond(),idx=Number(hg.dataset.homeGoal);if(s.goals?.[idx])s.goals[idx].done=hg.checked;writeBond(s);return}
 const pa=e.target.closest("[data-profile-action]");
 if(pa){const a=pa.dataset.profileAction;
  if(a==="back"){state.__profileScreen="hub";render();return}
  if(a==="person"){state.__profilePerson=pa.dataset.profilePerson==="partner"?"partner":"you";state.__profileScreen="person";render();return}
  if(a==="couple"){state.__profileScreen="couple";render();return}if(a==="relationship"){state.__profileScreen="relationship";render();return}if(a==="edit"){state.__profileScreen="edit";render();return}
  if(a==="achievements"){state.__profileScreen="achievements";render();return}
  if(a==="options"){state.__profileScreen="options";render();return}
  if(a==="close-options"){state.__profileScreen="hub";render();return}
  if(a==="settings"){state.__profileScreen="hub";setView("settings");return}
  if(a==="interests"){state.__interestSlot=state.__profileScreen==="person"?(state.__profilePerson==="partner"?"p2":"p1"):"couple";state.__profileScreen="interests";render();return}
  if(a==="save-relationship"){const f=document.querySelector("#relationship-profile-form");if(f){const d=new FormData(f);state.relationship=String(d.get("relationship")||"Couple");state.relationshipSince=String(d.get("relationshipSince")||"")||null;save()}state.__profileScreen="couple";render();return}if(a==="save-interests"){const selected=[...document.querySelectorAll("[data-interest].active, [data-interest].primary")].map(x=>x.dataset.interest),all=JSON.parse(localStorage.getItem("ignite-interests-v1")||"{}");all[state.__interestSlot||"couple"]=selected;localStorage.setItem("ignite-interests-v1",JSON.stringify(all));state.__profileScreen=state.__profileScreen="couple";render();return}
  if(a==="edit-photo"){const slot=pa.dataset.profileSlot;const input=document.createElement("input");input.type="file";input.accept="image/*";input.onchange=()=>{const file=input.files?.[0];if(!file)return;if(file.size>1024*1024){alert("Photo maksimal 1 MB.");return}const reader=new FileReader();reader.onload=()=>{state.profilePhotos[slot]=String(reader.result||"");save();render()};reader.readAsDataURL(file)};input.click();return}
  if(a==="delete"){if(confirm("Delete profile and all IGNITE data on this device? This cannot be undone.")){resetAllAppData()}return}
 }
 const interest=e.target.closest("[data-interest]");if(interest){interest.classList.toggle("active");interest.classList.toggle("primary");interest.classList.toggle("ghost");return}
 const photoOpen=e.target.closest("[data-memory-photo-open]");if(photoOpen){state.__memoryPhotoPreview=true;state.__selectedMemory=photoOpen.dataset.memoryPhotoOpen;renderMemoryDetail(state.__selectedMemory);return}
 if(e.target.closest("[data-memory-photo-close]")){delete state.__memoryPhotoPreview;renderMemoryDetail(state.__selectedMemory);return}
 const optOpen=e.target.closest("[data-memory-options-open]");if(optOpen){state.__memoryOptions=true;state.__selectedMemory=optOpen.dataset.memoryOptionsOpen;renderMemoryDetail(state.__selectedMemory);return}
 if(e.target.closest("[data-memory-options-close]")){delete state.__memoryOptions;renderMemoryDetail(state.__selectedMemory);return}
 const memEdit=e.target.closest("[data-memory-edit]");if(memEdit){delete state.__memoryOptions;state.__editingMemory=memEdit.dataset.memoryEdit;setView("memory-capture");return}
 const memShare=e.target.closest("[data-memory-share]");if(memShare){const m=getMemory(memShare.dataset.memoryShare);if(m){const text=(m.moment||"Memory")+" — "+(m.note||"");if(navigator.share)navigator.share({title:"IGNITE Memory",text}).catch(()=>{});else navigator.clipboard?.writeText(text).catch(()=>{})}return}
 const memMap=e.target.closest("[data-memory-map]");if(memMap){window.open("https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(memMap.dataset.memoryMap),"_blank","noopener");return}
 const tod=e.target.closest("[data-mini-tod]");if(tod){state.__todOpen=true;state.__todMode=tod.dataset.todMode||"truth";state.__todIndex=Math.floor(Math.random()*(state.__todMode==="truth"?starterTruth.length:starterDare.length));render();return}
 const todMode=e.target.closest("[data-tod-mode]");if(todMode){state.__todMode=todMode.dataset.todMode;state.__todIndex=Math.floor(Math.random()*(state.__todMode==="truth"?starterTruth.length:starterDare.length));render();return}
 const todNext=e.target.closest("[data-tod-next]");if(todNext){state.__todIndex=(state.__todIndex||0)+1;render();return}
 const todClose=e.target.closest("[data-tod-close]");if(todClose){delete state.__todOpen;render();return}
});
initEvents({state,load,save,clearAllTopicStorageOnce,app,esc,resetViewport,exportAppBackup,restoreAppBackup,resetAllAppData,syncModeTheme,journeys,readBond,writeBond,pickBond,TOPIC_MANAGER_KEYS,ROLE_KEYS,readContent,saveContent,cleanRole,getTopicStats,contentStats,contentTotal,initMechanic,mechanicAction,mechanicView,winnerLabel,isMechanicComplete,resetMechanic,renderMinigameMenu,minigameView,minigameAction,openMinigame,getProgress,getLevelInfo,startJourney,completeJourney,completeActivity,completeRitual,recordMinigamePlayed,achievementList,starterTruth,starterDare,renderMemorySummary,renderMemories,renderPreferences,renderFeatureSettings,handleVibeClick,handlePreferenceSubmit,surpriseContext,dynamicContext,renderContextSummary,handleMoodClick,saveMemory,getMemory,updateMemory,deleteMemory,toggleMemoryFavorite,recordVibe,recordInteraction,getPreferences,recordMemorySaved,recordOneMore,initAccessibility,coupleName,setView,render,renderBottomNav,renderJourneyGenerating,renderWelcome,renderVibeSelector,daysTogether,nextAnniversary,tonightSuggestion,homeModalOverlay,renderHome,renderBond,renderNames,renderIntro,renderMechanic,renderSession,renderMemoryCapture,renderComplete,renderMinigames,formatJourneyDate,renderJourney,renderJourneyDetail,profilePhoto,renderProfile,renderSettings,renderTopics,importContentSource,resetJourneyMechanics,setMode,generateJourney,begin,next,skip,exitSession,restart,saveNames,BACKUP_EXCLUDE_KEYS,since,start,now,year,day,prefs,vibes,adaptive,learned,progress,streak,modal,title,s,ctx,quotes,q,days,ms,n1,d,h,b,html,relationship,selected,j,correct,labels,winner,incompleteMechanic,dark,editing,cat,l,active,game,p,current,avatar,tags,slot,unlocked,dateValue,slots,TOPIC_MANAGER_LABELS,x,out,blob,tc,afterDark,ha,hq,hm,hma,hg,pa,interest,photoOpen,optOpen,memEdit,memShare,memMap,tod,todMode,todNext,todClose,g,category,topicAction,del,roleDel,sceneDel,finish});

}
