import {createRpsState,rpsPick,rpsWinner,createGuessColorState,guessColor,nextGuessRound} from "./rituals.js?v=20260924-01";
import {starterNormalCards,starterExplicitCards,starterTruth,starterDare,starterIntimateTruth,starterIntimateDare,randomUnused} from "./content.js?v=20260924-01";
import {chooseAdaptive} from "../features/adaptive.js?v=20260924-05";
const sessions=new Map();
function key(journey,step){return journey+":"+step}
export function resetMechanic(journey,step){sessions.delete(key(journey,step))}
export function initMechanic(journey,step){const k=key(journey,step);if(!sessions.has(k)){if(journey==="guess-color")sessions.set(k,{type:journey,data:createGuessColorState()});else if(journey==="rps")sessions.set(k,{type:journey,data:createRpsState()});else if(journey==="card"||journey==="explicit-card")sessions.set(k,{type:journey,data:{used:new Set(),revealed:false,text:"",count:0}});else if(journey==="tod"||journey==="intimate-tod")sessions.set(k,{type:journey,data:{mode:"truth",usedTruth:new Set(),usedDare:new Set(),revealed:false,text:"",count:0}})}return sessions.get(k)}
export function mechanicAction(journey,step,action,value){const s=initMechanic(journey,step);if(journey==="guess-color"){if(action==="guess")return guessColor(s.data,value);if(action==="next"){nextGuessRound(s.data);return null}}if(journey==="rps"){if(action==="pick")return rpsPick(s.data,value);if(action==="next"){if(s.data.roundsPlayed<s.data.targetRounds){s.data.stage="p1";s.data.p1Move=null;s.data.p2Move=null}return null}}if((journey==="card"||journey==="explicit-card")&&action==="draw"){const pool=journey==="explicit-card"?starterExplicitCards:starterNormalCards;const adaptive=chooseAdaptive(pool,{mode:journey==="explicit-card"?"dark":"normal",used:s.data.used});s.data.text=adaptive;const idx=pool.indexOf(adaptive);if(idx>=0)s.data.used.add(idx);s.data.revealed=true;s.data.count+=1;return s.data.text}if(journey==="tod"||journey==="intimate-tod"){if(action==="toggle"){s.data.mode=value;return null}if(action==="draw"){const truth=journey==="intimate-tod"?starterIntimateTruth:starterTruth;const dare=journey==="intimate-tod"?starterIntimateDare:starterDare;const pool=s.data.mode==="truth"?truth:dare;const used=s.data.mode==="truth"?s.data.usedTruth:s.data.usedDare;const adaptive=chooseAdaptive(pool,{mode:journey==="intimate-tod"?"dark":"normal",used});s.data.text=adaptive;const idx=pool.indexOf(adaptive);if(idx>=0)used.add(idx);s.data.revealed=true;s.data.count+=1;return s.data.text}}return null}
export function mechanicView(journey,step){return initMechanic(journey,step).data}
export function isMechanicComplete(journey,step){const d=mechanicView(journey,step);if(!journey)return true;if(journey==="guess-color")return d.roundsPlayed>=d.targetRounds;if(journey==="rps")return d.roundsPlayed>=d.targetRounds&&d.stage==="result";return d.revealed===true}
export function winnerLabel(state,names){const w=rpsWinner(state);if(w===null)return"Seri";return(w===0?names.p1:names.p2)+" menang"}
