import {initMechanic,mechanicAction,mechanicView,winnerLabel,isMechanicComplete,resetMechanic} from "./journey/mechanics.js?v=20260928-02";
import {renderMinigameMenu,minigameView,minigameAction,openMinigame} from "./minigames/index.js?v=20260928-02";
import {getProgress,getLevelInfo,startJourney as progressionStartJourney,completeJourney,completeActivity,completeRitual,recordMinigamePlayed,achievementList} from "./progression.js?v=20260928-02";
import {starterNormalCards,starterExplicitCards,starterTruth,starterDare,starterIntimateTruth,starterIntimateDare} from "./journey/content.js?v=20260928-02";
import {allKingNormalCommands,allKingDarkCommands,allRoleplayNormalRoles,allRoleplayDarkRoles} from "./data/topics.js?v=20260928-02";
import {renderMemorySummary,renderMemories,renderPreferences,renderFeatureSettings,handleVibeClick,handlePreferenceSubmit,surpriseContext,dynamicContext,renderContextSummary,handleMoodClick} from "./features/ui.js?v=20260928-02";
import {saveMemory} from "./features/memories.js?v=20260928-02";
import {recordVibe,recordInteraction} from "./features/adaptive.js?v=20260928-02";
import {getPreferences} from "./features/preferences.js?v=20260928-02";
import {recordMemorySaved,recordOneMore} from "./progression.js?v=20260928-02";
import {initAccessibility} from "./ui/accessibility.js?v=20260928-02";

const STORAGE_KEY="ignite-redesign-v4";
const TOPIC_CLEAR_VERSION="20260926-clear-all-topics";
function clearAllTopicStorageOnce(){
  if(localStorage.getItem(TOPIC_CLEAR_VERSION)==="done")return;
  ["ignite-active-content-v1","ignite-active-topics-v1","ignite-custom-topics-v1","ignite-content-v1"].forEach(k=>localStorage.removeItem(k));
  localStorage.setItem(TOPIC_CLEAR_VERSION,"done");
}
const state={names:{p1:"",p2:"",couple:""},relationship:"Couple",relationshipSince:null,currentJourney:null,step:0,view:"home",mode:"normal"};
const journeys={
 normal:{id:"normal",title:"Normal Journey",subtitle:"Talk, play, and get a little closer.",mood:"Romantic · Playful · Warm",steps:[
  {kind:"ritual",mechanic:"guess-color",icon:"🎴",title:"Warm Up",text:"Tebak warna kartu sebelum kartu dibuka. Lima ronde cukup untuk mengubah suasana.",action:"Continue"},
  {kind:"activity",mechanic:"card",icon:"♡",title:"Talk Card",text:"Buka kartu satu per satu. Kalian menentukan kapan cukup dan lanjut ke tahap berikutnya.",action:"Continue"},
  {kind:"ritual",mechanic:"rps",icon:"✊",title:"Change the Energy",text:"Mainkan Rock Paper Scissors. Lima ronde untuk mengubah tempo.",action:"Continue"},
  {kind:"activity",mechanic:"tod",icon:"◇",title:"Truth or Dare",text:"Buka prompt satu per satu. Pilih Truth atau Dare, lalu lanjut saat kalian siap.",action:"Continue"},
  {kind:"activity",mechanic:"card",icon:"♡",title:"One More Card",text:"Satu ruang terakhir untuk sebuah kartu. Ambil sebanyak yang kalian mau sebelum menutup Journey.",action:"Continue"},
  {kind:"closing",icon:"♥",title:"Close the Journey",text:"Apa satu hal kecil dari pasanganmu yang paling kamu nikmati saat ini?",action:"Finish Journey"}]},
 dark:{id:"dark",title:"After Dark",subtitle:"A more intimate journey for two.",mood:"Intimate · Daring · Tasteful",steps:[
  {kind:"ritual",mechanic:"guess-color",icon:"🎴",title:"Set the Mood",text:"Mulai perlahan dengan tebak warna kartu. Kalian bisa berhenti kapan saja.",action:"Continue"},
  {kind:"activity",mechanic:"explicit-card",icon:"🔥",title:"Explicit Card",text:"Buka kartu satu per satu. Konten After Dark membutuhkan persetujuan dan kenyamanan kalian berdua.",action:"Continue"},
  {kind:"ritual",mechanic:"rps",icon:"✊",title:"Change the Energy",text:"Gunakan lima ronde singkat untuk mengubah tempo.",action:"Continue"},
  {kind:"activity",mechanic:"intimate-tod",icon:"◇",title:"Intimate Truth or Dare",text:"Buka prompt satu per satu. Pilih yang terasa nyaman. Kalian tetap memegang kendali.",action:"Continue"},
  {kind:"activity",mechanic:"roleplay",icon:"🎭",title:"Roleplay",text:"Masuk ke sebuah karakter dan adegan. Kalian menentukan sendiri kapan cukup.",action:"Continue"},
  {kind:"closing",icon:"♥",title:"Close the Journey",text:"Selesai. Tidak perlu mengejar apa pun — cukup nikmati momennya.",action:"Finish Journey"}]}
};

const app=document.querySelector("#app");
function load(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(saved){state.names=saved.names||state.names;state.relationship=saved.relationship||"Couple";state.relationshipSince=saved.relationshipSince||null;state.currentJourney=saved.currentJourney||null;state.step=Number(saved.step)||0;state.view=saved.view||"home";state.mode=saved.mode==="dark"?"dark":"normal";state.__selectedJourney=Number.isInteger(saved.__selectedJourney)?saved.__selectedJourney:null;if(state.view==="generating"){state.view="home";delete state.__journeyTargetSteps;delete state.__journeyRoleplayOpen;delete state.__journeyRoleplayDone}}}catch(e){state.view="home"}}
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch(e){console.warn("[IGNITE] state save failed",e)}}
const BACKUP_EXCLUDE_KEYS=new Set(["ignite-topic-clear-v1"]);
function appStorageSnapshot(){const data={};for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key&&key.startsWith("ignite-")&&!BACKUP_EXCLUDE_KEYS.has(key))data[key]=localStorage.getItem(key)}return data}
function downloadText(filename,text,type="application/json"){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
function exportAppBackup(){downloadText("ignite-backup-"+new Date().toISOString().slice(0,10)+".json",JSON.stringify({format:"ignite-backup",version:1,exportedAt:new Date().toISOString(),data:appStorageSnapshot()},null,2))}
function restoreAppBackup(data){if(!data||data.format!=="ignite-backup"||!data.data||typeof data.data!=="object")throw new Error("Invalid IGNITE backup.");for(let i=localStorage.length-1;i>=0;i--){const key=localStorage.key(i);if(key&&key.startsWith("ignite-"))localStorage.removeItem(key)}for(const key of Object.keys(data.data))if(key.startsWith("ignite-")&&!BACKUP_EXCLUDE_KEYS.has(key))localStorage.setItem(key,String(data.data[key]??""));localStorage.setItem(TOPIC_CLEAR_VERSION,"done");sessionStorage.setItem("ignite-welcome-seen","1");location.reload()}
function resetAllAppData(){if(!window.confirm("Reset all IGNITE data on this device? This cannot be undone."))return;for(let i=localStorage.length-1;i>=0;i--){const key=localStorage.key(i);if(key&&key.startsWith("ignite-"))localStorage.removeItem(key)}sessionStorage.removeItem("ignite-welcome-seen");location.reload()}
function coupleName(){const level=getLevelInfo(getProgress().xp);const quotes={1:"Every story starts with a spark.",2:"Two people, one little world.",3:"The closer you get, the more you discover.",4:"In sync, one moment at a time.",5:"You found your rhythm. Keep the fire alive.",6:"Some connections grow deeper with every moment.",7:"Two hearts, one unstoppable rhythm.",8:"This is your story. Keep the fire alive."};return quotes[level.level]||quotes[1]}
function esc(v){return String(v).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]})}
function resetViewport(){
 try{window.scrollTo({top:0,left:0,behavior:"auto"})}catch{window.scrollTo(0,0)}
 if(document.documentElement)document.documentElement.scrollTop=0;
 if(document.body)document.body.scrollTop=0;
}
function setView(view){state.view=view;save();render();requestAnimationFrame(resetViewport)}
function render(){app.dataset.igniteMode=state.mode==="dark"?"dark":"normal";if(state.view==="generating")renderJourneyGenerating();else if(state.view==="welcome")renderWelcome();else if(state.view==="home")renderHome();else if(state.view==="names")renderNames();else if(state.view==="intro")renderIntro();else if(state.view==="session")renderSession();else if(state.view==="complete")renderComplete();else if(state.view==="minigames")renderMinigames();else if(state.view==="profile")renderProfile();else if(state.view==="settings")renderSettings();else if(state.view==="journey")renderJourney();else if(state.view==="journey-detail")renderJourneyDetail();else if(state.view==="memories")app.innerHTML=renderMemories(renderBottomNav("memories"));else if(state.view==="memory-capture")renderMemoryCapture();else if(state.view==="preferences")app.innerHTML=renderPreferences();else if(state.view==="topics")renderTopics();else if(state.view==="bond")renderBond();else{state.view="home";save();renderHome()}}
function renderBottomNav(active="home"){
 return '<nav class="bottom-nav" aria-label="Main navigation">'+
 '<button class="bottom-nav-item '+(active==="home"?"active":"")+'" data-action="home" aria-label="Home"><span>⌂</span><small>Home</small></button>'+
 '<button class="bottom-nav-item '+(active==="play"?"active":"")+'" data-action="minigames" aria-label="Play"><span>♧</span><small>Play</small></button>'+
 '<button class="bottom-nav-item '+(active==="memories"?"active":"")+'" data-action="memories" aria-label="Memories"><span>♡</span><small>Memories</small></button>'+
 '<button class="bottom-nav-item '+(active==="profile"?"active":"")+'" data-action="profile" aria-label="Profile"><span>⌁</span><small>Profile</small></button>'+
 '</nav>';
}
function renderJourneyGenerating(){app.innerHTML='<section class="journey-generating"><div class="journey-generating-orb" aria-hidden="true"></div><div class="eyebrow">BUILDING YOUR JOURNEY</div><h1>Give us a moment.</h1><p>IGNITE sedang menyusun '+esc(String(state.__journeyTargetSteps||5))+' steps untuk kalian.</p><div class="journey-loader" role="status" aria-live="polite"><span></span><span></span><span></span></div><small>Memilih ritme, variasi, dan urutan perjalanan…</small></section>'}
function renderWelcome(){
 app.innerHTML='<section class="welcome-cinematic"><div class="welcome-scene" aria-hidden="true"><div class="welcome-glow"></div><div class="welcome-silhouette welcome-silhouette-a"></div><div class="welcome-silhouette welcome-silhouette-b"></div><div class="welcome-ring"></div><div class="welcome-grain"></div></div><div class="welcome-cinematic-copy"><div class="welcome-mark">✦</div><div class="eyebrow">COUPLE INTIMACY GAMES</div><h1>IGNITE</h1><p>Play. Connect. Ignite.</p><div class="welcome-divider"></div><button class="btn primary full welcome-enter" data-action="enter">ENTER TOGETHER <span>→</span></button><small class="welcome-note">A private space made for two.</small></div></section>';
}
function renderVibeSelector(){const selected=getPreferences().vibes[0]||"Romantic";const vibes=["Romantic","Playful","Deep","Competitive","Spontaneous","Intimate"];return '<section class="card vibe-selector"><div class="eyebrow">VIBE</div><h3>What feels right tonight?</h3><p class="muted">IGNITE akan menyesuaikan pilihan berikutnya dengan vibe kalian.</p><div class="choice-grid preference-grid">'+vibes.map(v=>'<button type="button" class="btn choice '+(selected===v?"primary":"ghost")+'" data-vibe-home="'+esc(v)+'" aria-pressed="'+(selected===v?"true":"false")+'">'+esc(v)+'</button>').join("")+'</div></section>'}
function daysTogether(){
 const since=state.relationshipSince;
 if(!since)return null;
 const start=new Date(since);
 if(Number.isNaN(start.getTime()))return null;
 return Math.max(1,Math.floor((Date.now()-start.getTime())/86400000));
}
function tonightSuggestion(){
 const prefs=JSON.parse(localStorage.getItem("ignite-preferences-v1")||'{"vibes":["Romantic"]}');
 const vibes=Array.isArray(prefs.vibes)?prefs.vibes:[];
 const adaptive=JSON.parse(localStorage.getItem("ignite-adaptive-v1")||"{}");
 const learned=Object.entries(adaptive.vibes||{}).sort((a,b)=>b[1]-a[1])[0]?.[0]||"";
 const progress=getProgress();
 const streak=Math.max(0,Number(progress.stats?.currentStreak)||0);
 if(state.mode==="dark")return{title:streak>=3?"Keep the fire alive":"Intimate Connection",text:streak>=3?"Your rhythm is building. Take the next moment at your own pace.":"A slower, more intentional After Dark moment for two."};
 if(vibes.includes("Deep")||learned==="Deep")return{title:"Deep Connection",text:"Slow down and make room for a conversation that matters."};
 if(vibes.includes("Playful")||learned==="Playful")return{title:"Playful Connection",text:"A light game can turn tonight into a shared little story."};
 if(vibes.includes("Competitive")||learned==="Competitive")return{title:"Game Night",text:"Pick a game, keep the score, and see where the night goes."};
 if(vibes.includes("Spontaneous")||learned==="Spontaneous")return{title:"Try Something New",text:"Let IGNITE change the pace and surprise you tonight."};
 if(streak>=3)return{title:"Keep the Rhythm",text:"You’ve been showing up for each other. Keep tonight simple and meaningful."};
 return{title:"Playful Connection",text:"A simple way to play, talk, and feel a little closer."};
}
function renderHome(){
 const dark=state.mode==="dark",days=daysTogether(),s=tonightSuggestion();
 let ms=[];try{ms=JSON.parse(localStorage.getItem("ignite-memories-v1")||"[]")}catch{} if(!Array.isArray(ms))ms=[];
 ms=ms.sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,3);
 const names=[state.names.p1||"You",state.names.p2||"Your partner"];
 let h='<section class="home-v2">';
 h+='<header class="home-v2-header"><div class="home-v2-brand"><b>♧</b><div><strong>IGNITE</strong><small>Our story, every day. · YOUR SPACE FOR TWO</small></div></div><button class="icon-btn" data-action="profile" aria-label="Open profile">♧</button></header>';
 h+='<section class="home-v2-hero"><div class="home-v2-greeting">GOOD EVENING,</div><h1>'+esc(names[0])+' &amp; '+esc(names[1])+' <span>♥</span></h1><p>♡ '+(days??"—")+' days together</p><small class="home-v2-rhythm">YOUR RHYTHM · '+(days??"—")+' days together</small><div class="home-v2-quote">“Different people, same favorite person.” <span>♥</span></div></section>';
 h+='<section class="home-v2-section"><div class="home-v2-head"><h2>Our Journey</h2><button class="text-link" data-action="journey">See All</button></div><article class="home-v2-journey card"><div class="journey-art"><span>♥</span><strong>'+(days??"—")+'</strong><small>Days Together</small></div><div class="journey-line"><i></i><i></i><i class="on"></i><i></i></div><div class="journey-labels"><span>First Date</span><span>100 Days</span><span>Today</span><span>Next Anniversary</span></div><button class="btn ghost full" data-action="journey">View Timeline →</button></article></section>';
 h+='<section class="home-v2-section"><div class="home-v2-head"><h2>Today’s Moment</h2><button class="text-link" data-action="minigames">See All</button></div><article class="home-v2-moment card"><div class="moment-art">✦</div><div class="eyebrow">DAILY MOMENT</div><h3>'+esc(s.title)+'</h3><p>'+esc(s.text)+'</p><small>◷ 1–3 minutes</small><button class="btn primary full" data-action="start" data-journey="'+(dark?"dark":"normal")+'">Start Moment →</button></article></section>';
 h+='<section class="home-v2-section"><div class="home-v2-head"><h2>Quick Connection</h2></div><div class="home-v2-quick"><button data-action="bond">♡<small>Ask<br>Something</small></button><button data-action="memory-capture">▣<small>Save a<br>Memory</small></button><button data-action="profile">➤<small>Send a<br>Message</small></button><button data-action="minigames">♧<small>Play<br>Together</small></button></div></section>';
 h+='<section class="home-v2-section"><div class="home-v2-head"><h2>Recent Memories</h2><button class="text-link" data-action="memories">See All</button></div><div class="home-v2-memory-row">'+(ms.length?ms.map(m=>'<article class="home-v2-memory" data-action="memories"><div>'+(m.photo?'<img src="'+esc(m.photo)+'" alt="">':'♥')+'</div><b>'+esc(m.moment||m.journey||"Special moment")+'</b><small>'+new Date(m.date||Date.now()).toLocaleDateString("id-ID")+'</small></article>').join(""):'<div class="home-v2-empty" data-action="memory-capture">Save your first memory ♥</div>')+'</div></section>';
 h+='<section class="home-v2-section"><article class="home-v2-next card"><div><span class="eyebrow">WHAT’S NEXT?</span><h3>Next Anniversary</h3><strong>♡ <small>Make it count</small></strong><p>Add your relationship date in Profile → Settings.</p></div><span>🎁</span><b>›</b></article></section>';
 h+='<section class="home-v2-section"><div class="home-v2-head"><h2>Today’s Motivation</h2></div><article class="home-v2-quote-card">“Small moments today, big memories tomorrow.” <span>♥</span></article></section>';
 h+=renderBottomNav("home")+'</section>';app.innerHTML=h;
}
const BOND_KEY="ignite-bond-v1";
const BOND_PROMPTS={daily:["Apa satu hal kecil yang membuatmu merasa dekat denganku hari ini?","Kalau malam ini hanya punya satu jam bersama, kamu ingin menghabiskannya bagaimana?","Apa momen kecil kita akhir-akhir ini yang ingin kamu ulang?","Hal apa dari pasanganmu yang akhir-akhir ini paling kamu hargai?"],deep:["Apa hal tentang masa depan kita yang paling ingin kamu bangun bersama?","Kapan kamu merasa paling aman untuk menjadi dirimu sendiri bersamaku?","Apa sesuatu yang ingin kamu pelajari tentang pasanganmu tahun ini?","Apa satu kebiasaan kecil yang bisa membuat hubungan kita terasa lebih hangat?"],quiz:["Siapa yang lebih mungkin mengajak liburan dadakan?","Siapa yang lebih cepat bilang ayo coba saat ada hal baru?","Siapa yang biasanya lebih dulu mencairkan suasana setelah salah paham?"]};
function readBond(){try{const raw=JSON.parse(localStorage.getItem(BOND_KEY)||"{}");return{...raw,favorites:Array.isArray(raw?.favorites)?raw.favorites:[],goals:Array.isArray(raw?.goals)?raw.goals:[]}}catch{return{favorites:[],goals:[]}}}
function writeBond(v){localStorage.setItem(BOND_KEY,JSON.stringify(v));return v}
function pickBond(type,current=""){const pool=BOND_PROMPTS[type]||BOND_PROMPTS.daily;const choices=pool.filter(x=>x!==current);return choices[Math.floor(Math.random()*choices.length)]||pool[0]}
function renderBond(){
 const b=readBond(),current=b.dailyCurrent||pickBond("daily"),deep=b.deepCurrent||pickBond("deep"),quiz=b.quizCurrent||pickBond("quiz");
 if(!b.dailyCurrent)b.dailyCurrent=current;
 if(!b.deepCurrent)b.deepCurrent=deep;
 if(!b.quizCurrent)b.quizCurrent=quiz;
 writeBond(b);
 let html='<section class="bond-v1"><div class="bond-v1-top"><div></div><div class="brand">BOND</div><div></div></div><section class="bond-v1-hero"><div class="eyebrow">CONNECTION, BEYOND THE GAME</div><h1>Make space<br>for each other.</h1><p>Small questions can become big memories.</p></section><section class="bond-v1-grid">';
 html+='<article class="bond-v1-card featured"><span class="eyebrow">DAILY QUESTION</span><h3>'+esc(current)+'</h3><div><button class="btn ghost" data-bond-action="new" data-bond-type="daily">Another</button><button class="btn primary" data-bond-action="favorite">Save</button></div></article>';
 html+='<article class="bond-v1-card"><span class="bond-v1-icon">◌</span><span class="eyebrow">COUPLE QUIZ</span><h3>'+esc(quiz)+'</h3><button class="btn ghost" data-bond-action="new" data-bond-type="quiz">New Question</button></article>';
 html+='<article class="bond-v1-card"><span class="bond-v1-icon">✦</span><span class="eyebrow">DEEP TALK</span><h3>'+esc(deep)+'</h3><button class="btn ghost" data-bond-action="new" data-bond-type="deep">Go Deeper</button></article>';
 html+='<article class="bond-v1-card"><span class="bond-v1-icon">♡</span><span class="eyebrow">FAVORITES</span><h3>'+b.favorites.length+' saved</h3><div class="bond-favorites">'+(b.favorites.length?b.favorites.map(x=>'<p>'+esc(x)+'</p>').join(""):'<p>Save questions you want to revisit.</p>')+'</div></article>';
 html+='<article class="bond-v1-card goals"><span class="bond-v1-icon">∞</span><span class="eyebrow">RELATIONSHIP GOALS</span><h3>Small things, together.</h3><form id="bond-goal-form"><input name="goal" maxlength="100" placeholder="Add a small goal"><button class="btn primary full">Add Goal</button></form><div class="bond-goals">'+(b.goals.length?b.goals.map((g,i)=>'<label><input type="checkbox" data-bond-goal="'+i+'" '+(g.done?"checked":"")+'><span>'+esc(g.text)+'</span></label>').join(""):'<p class="muted">No goals yet.</p>')+'</div></article>';
 html+='</section>'+renderBottomNav("home")+'</section>';app.innerHTML=html;
}
function renderNames(){
 const relationship=state.relationship||"Couple";
 const selected=v=>relationship===v?" selected":"";
 app.innerHTML='<section class="setup-shell"><div class="setup-art" aria-hidden="true"><div class="setup-orb"></div><div class="setup-spark">✦</div></div><div class="setup-top"><span class="setup-step">01</span><span>IGNITE</span></div><div class="setup-copy"><div class="eyebrow">LET’S BEGIN TOGETHER</div><h1>Let’s get to<br>know each other.</h1><p>Siapa yang akan berbagi momen malam ini?</p></div><form class="card setup-form" id="name-form"><div class="field"><label>YOUR NAME</label><input name="p1" maxlength="30" value="'+esc(state.names.p1)+'" placeholder="Nama kamu" autocomplete="given-name" required></div><div class="field"><label>YOUR LOVE</label><input name="p2" maxlength="30" value="'+esc(state.names.p2)+'" placeholder="Nama pasangan" autocomplete="name" required></div><div class="field"><label>RELATIONSHIP</label><select name="relationship"><option value="Couple"'+selected("Couple")+'>Couple</option><option value="Married"'+selected("Married")+'>Married</option><option value="Dating"'+selected("Dating")+'>Dating</option><option value="Other"'+selected("Other")+'>Other</option></select></div><button class="btn primary full setup-submit">Start Our Journey <span>→</span></button><p class="setup-note">Your names stay on this device unless you choose to export your IGNITE data.</p></form></section>';
}
function renderIntro(){
 const j=state.currentJourney;if(!j){setView("home");return}const dark=j.id==="dark",steps=j.steps.length;
 let html='<section class="intro-v2"><header class="intro-v2-header"><button class="icon-btn" data-action="home" aria-label="Back">←</button><span>IGNITE</span><span class="intro-v2-mode">'+(dark?"AFTER DARK 18+":"NORMAL")+'</span></header>';
 html+='<section class="intro-v2-hero"><div class="intro-v2-mark">'+(dark?"🔥":"✦")+'</div><span class="eyebrow">'+esc(j.mood)+'</span><h1>'+esc(j.title)+'</h1><p>'+esc(j.subtitle)+'</p></section>';
 html+='<section class="intro-v2-preview"><div><span class="eyebrow">YOUR FLOW</span><strong>'+steps+' moments</strong></div><div class="intro-v2-dots">'+j.steps.map((x,i)=>'<i class="'+(i===0?"active":"")+'"></i>').join("")+'</div><small>IGNITE sets the rhythm. You decide when to continue.</small></section>';
 if(dark)html+='<label class="intro-v2-consent"><input id="consent" type="checkbox"><span>We are both 18+ and agree to continue. We can stop at any time.</span></label>';
 html+='<button class="btn primary full intro-v2-start" data-action="begin">'+(dark?"Enter After Dark":"Begin Together")+' →</button><button class="btn ghost full" data-action="home">Maybe later</button></section>';app.innerHTML=html;
}
function renderMechanic(s){
 if(!s.mechanic)return"";
 if(s.mechanic==="roleplay"){
  if(!state.__journeyRoleplayOpen)return '<div class="mechanic journey-roleplay"><div class="mechanic-note">Pilih karakter dan adegan saat kalian siap. Kalian tetap memegang kendali.</div><button class="btn primary full" data-mechanic="open-roleplay">Open Roleplay →</button></div>';
  return '<div class="mechanic journey-roleplay"><div class="mechanic-note">Roleplay aktif. Kalian bisa lanjut kapan saja.</div>'+minigameView(state.names)+'<button class="btn ghost full" data-mechanic="finish-roleplay">Done with Roleplay →</button></div>';
 }
 const d=mechanicView(s.mechanic,state.step);
 if(s.mechanic==="guess-color"){
  const correct=d.lastGuess===d.currentSuit.color;
  return '<div class="mechanic"><div class="round-label">Round '+Math.min(d.roundsPlayed+1,d.targetRounds)+' / '+d.targetRounds+'</div>'+
   (d.revealed?'<div class="mechanic-result '+(correct?"success":"miss")+'"><div class="result-kicker">'+(correct?"BENAR":"BELUM TEPAT")+'</div><strong>'+d.currentSuit.symbol+" "+(d.currentSuit.color==="red"?"Merah":"Hitam")+'</strong><span>'+(correct?"Tebakan kalian tepat.":"Kartu yang terbuka berbeda dari tebakan.")+'</span></div>':'<div class="mechanic-note">Pilih warna kartu sebelum dibuka.</div>')+
   '<div class="choice-grid"><button class="btn choice" data-mechanic="guess" data-value="red" '+(d.revealed?"disabled":"")+'>🔴 Merah</button><button class="btn choice" data-mechanic="guess" data-value="black" '+(d.revealed?"disabled":"")+'>⚫ Hitam</button></div>'+
   (d.revealed?'<button class="btn ghost full" data-mechanic="next-round">Next Round</button>':"")+'</div>';
 }
 if(s.mechanic==="rps"){
  const labels={rock:"✊ Batu",paper:"✋ Kertas",scissors:"✌️ Gunting"};
  const winner=winnerLabel(d,state.names);
  return '<div class="mechanic"><div class="round-label">Round '+Math.min(d.roundsPlayed+1,d.targetRounds)+' / '+d.targetRounds+'</div>'+
   (d.stage==="result"?'<div class="mechanic-result '+(winner==="Seri"?"draw":"success")+'"><div class="result-kicker">HASIL RONDE</div><strong>'+esc(winner)+'</strong><span>'+esc(state.names.p1||"Player 1")+'  ·  '+labels[d.p1Move]+' &nbsp; vs &nbsp; '+esc(state.names.p2||"Player 2")+'  ·  '+labels[d.p2Move]+'</span></div>':'<div class="mechanic-note">'+(d.stage==="p1"?esc(state.names.p1||"Player 1")+" pilih dulu, lalu oper HP.":esc(state.names.p2||"Player 2")+" pilih sekarang.")+'</div>')+
   '<div class="choice-grid three"><button class="btn choice" data-mechanic="pick" data-value="rock" '+(d.stage==="result"?"disabled":"")+'>✊ Batu</button><button class="btn choice" data-mechanic="pick" data-value="paper" '+(d.stage==="result"?"disabled":"")+'>✋ Kertas</button><button class="btn choice" data-mechanic="pick" data-value="scissors" '+(d.stage==="result"?"disabled":"")+'>✌️ Gunting</button></div>'+
   (d.stage==="result"?'<button class="btn ghost full" data-mechanic="rps-next">Next Round</button>':"")+'</div>';
 }
 if(s.mechanic==="card"||s.mechanic==="explicit-card"){return '<div class="mechanic"><div class="round-label">'+(d.count?("Card "+d.count):"Ready for a card")+'</div><button class="card reveal-card '+(d.revealed?'disabled':'')+'" '+(d.revealed?'disabled':'data-mechanic="draw-card"')+'>'+(d.revealed?'<span>'+esc(d.text)+'</span>':'<span>♡<br><small>Tap to reveal</small></span>')+'</button>'+(d.revealed?'<button class="btn ghost full" data-mechanic="next-card">Next Card →</button>':'')+'</div>';}
 if(s.mechanic==="tod"||s.mechanic==="intimate-tod"){return '<div class="mechanic"><div class="toggle-row"><button class="btn '+(d.mode==="truth"?"primary":"ghost")+'" data-mechanic="tod-mode" data-value="truth">Truth</button><button class="btn '+(d.mode==="dare"?"primary":"ghost")+'" data-mechanic="tod-mode" data-value="dare">Dare</button></div><div class="round-label">'+(d.count?("Prompt "+d.count):"Ready for a prompt")+'</div><button class="card reveal-card '+(d.revealed?'disabled':'')+'" '+(d.revealed?'disabled':'data-mechanic="tod-draw"')+'>'+(d.revealed?'<span>'+esc(d.text)+'</span>':'<span>◇<br><small>Tap to reveal</small></span>')+'</button>'+(d.revealed?'<button class="btn ghost full" data-mechanic="next-tod">Next Prompt →</button>':'')+'</div>';}
 return"";
}
function renderSession(){
 const j=state.currentJourney;if(!j){setView("home");return}const s=j.steps[state.step],total=j.steps.length,progress=Math.round(((state.step+1)/total)*100);
 if(s.mechanic&&s.mechanic!=="roleplay")initMechanic(s.mechanic,state.step);
 const incompleteMechanic=s.mechanic==="roleplay"?!state.__journeyRoleplayDone:(s.mechanic?!isMechanicComplete(s.mechanic,state.step):false);
 const dark=j.id==="dark";
 let html='<section class="session-v2"><header class="session-v2-header"><button class="icon-btn" data-action="exit" aria-label="Exit">×</button><div><span class="eyebrow">'+(dark?"AFTER DARK":"JOURNEY")+'</span><strong>Moment '+(state.step+1)+' / '+total+'</strong></div><span class="session-v2-percent">'+progress+'%</span></header>';
 html+='<div class="session-v2-progress"><span style="width:'+progress+'%"></span></div><section class="session-v2-card"><div class="session-v2-art">'+esc(s.icon||"♥")+'</div><div class="session-v2-meta"><span>'+esc(s.kind||"moment")+'</span><span>'+Math.max(1,state.step+1)+' of '+total+'</span></div><h1>'+esc(s.title)+'</h1><p class="session-v2-copy">'+esc(s.text)+'</p>'+renderMechanic(s)+'<div class="session-v2-actions"><button class="btn ghost" data-action="skip">Skip</button><button class="btn primary" data-action="next" '+(incompleteMechanic?"disabled":"")+'>'+esc(s.action)+' →</button></div></section><footer class="session-v2-footer"><span>♥</span>'+esc(coupleName())+'</footer></section>';
 app.innerHTML=html;
}
function renderMemoryCapture(){app.innerHTML='<section class="complete-shell"><div class="complete-top"><button class="btn ghost" data-action="memories">←</button><span>IGNITE</span><span></span></div><article class="card complete-card"><div class="mark">♡</div><div class="eyebrow">ADD A MEMORY</div><h2>Keep this one.</h2><p>Save a small moment from tonight — privately on this device.</p><form id="memory-form" class="memory-capture"><div class="field"><label for="memory-moment">MEMORY</label><input id="memory-moment" name="moment" maxlength="80" placeholder="Our favorite moment..." required></div><div class="field"><label for="memory-note">NOTE</label><textarea id="memory-note" name="note" maxlength="240" placeholder="Anything you want to remember (optional)"></textarea></div><div class="field"><label for="memory-photo">PHOTO</label><input id="memory-photo" name="photo" type="file" accept="image/*"></div><button class="btn primary full">Save Memory</button></form></article></section>'}
function renderComplete(){
 const l=getLevelInfo(getProgress().xp);
 app.innerHTML='<section class="complete-v2"><div class="complete-v2-glow"></div><header><span>IGNITE</span><span>JOURNEY COMPLETE</span></header><section class="complete-v2-card"><div class="complete-v2-mark">♥</div><span class="eyebrow">YOU SHOWED UP FOR EACH OTHER</span><h1>How was tonight?</h1><p>Choose one word to keep with this moment.</p><div class="ending-vibes"><button class="btn choice" data-ending="Fun">Fun</button><button class="btn choice" data-ending="Closer">Closer</button><button class="btn choice" data-ending="Meaningful">Meaningful</button><button class="btn choice" data-ending="Unexpected">Unexpected</button></div><div class="complete-v2-level"><div><small>TOGETHER</small><strong>LEVEL '+l.level+'</strong></div><div><small>REWARD</small><strong>+'+Number(getProgress().stats?.xpEarned||0)+' XP</strong></div></div><form id="memory-form" class="memory-capture"><label class="sr-only" for="complete-memory-note">NOTE</label><textarea id="complete-memory-note" name="note" maxlength="240" placeholder="One line about this moment (optional)"></textarea><label class="sr-only" for="complete-memory-photo">PHOTO</label><input id="complete-memory-photo" name="photo" type="file" accept="image/*"><button class="btn primary full">Save This Moment</button></form><button class="btn ghost full" data-action="again">Play Again</button><button class="btn ghost full" data-action="home">Done for now</button></section></section>';
}
function renderMinigames(){
 const active=state.__minigameActive,body=active?minigameView(state.names):renderMinigameMenu(state.mode);
 const filter=state.__playFilter||"all";
 let h='<section class="play-v2">';
 if(!active){const dark=state.mode==="dark";h+='<header class="play-v2-header"><div><h1>PLAY</h1><p>Games &amp; tonight’s journey.</p></div><span class="play-v2-mode">'+(dark?"After Dark 18+":"Normal")+'</span></header><div class="play-v2-tabs" role="tablist" aria-label="Game filters"><button type="button" class="'+(filter==="all"?"active":"")+'" data-play-filter="all" aria-selected="'+(filter==="all"?"true":"false")+'"'>All Games</button><button type="button" class="'+(filter==="normal"?"active":"")+'" data-play-filter="normal" aria-selected="'+(filter==="normal"?"true":"false")+'"'>Normal</button><button type="button" class="'+(filter==="dark"?"active":"")+'" data-play-filter="dark" aria-selected="'+(filter==="dark"?"true":"false")+'"'>After Dark 18+</button></div><section class="play-v2-feature card"><div class="feature-art">✦</div><div><span class="eyebrow">FEATURED</span><h2>Journey</h2><p>Start a meaningful conversation together.</p></div><button data-action="start" data-journey="'+(dark?"dark":"normal")+'">→</button></section><div class="home-v2-head"><h2>All Games</h2><button class="text-link" data-action="journey">History</button></div>'+body+'<section class="play-v2-surprise card"><b>Not sure what to do?</b><small>Let IGNITE give you a suggestion based on your vibe today.</small><button class="btn primary" data-action="surprise">Surprise Me</button></section>';}
 else h+='<div class="play-v2-active"><button class="btn ghost" data-action="minigames-menu">← All Games</button><span class="play-v2-mode">'+(state.mode==="dark"?"After Dark 18+":"Normal")+'</span></div>'+body;
 h+=(active?'':renderBottomNav("play"))+'</section>';app.innerHTML=h;
}
function formatJourneyDate(value){
 try{return new Intl.DateTimeFormat("id-ID",{day:"numeric",month:"short",year:"numeric"}).format(new Date(value))}
 catch{return "Recent"}
}
function renderJourney(){
 const p=getProgress(),records=Array.isArray(p.journeyHistory)?p.journeyHistory:[],level=getLevelInfo(p.xp);
 let html='<section class="journey-v2"><header class="journey-v2-header"><button class="icon-btn" data-action="home" aria-label="Back">←</button><div><span class="eyebrow">YOUR STORY</span><h1>JOURNEY</h1></div><span class="journey-v2-level">LV '+level.level+'</span></header>';
 html+='<section class="journey-v2-hero"><div class="journey-v2-orb">♥</div><div><span class="eyebrow">TOGETHER</span><h2>One moment at a time.</h2><p>Your completed journeys become part of your shared story.</p></div></section>';
 html+='<section class="journey-v2-stats"><article><span>JOURNEYS</span><strong>'+records.length+'</strong><small>completed together</small></article><article><span>XP TOGETHER</span><strong>'+p.xp+'</strong><small>Level '+level.level+' · '+esc(level.title)+'</small></article></section>';
 html+='<div class="journey-v2-section-head"><div><span class="eyebrow">YOUR STORY</span><h2>Past moments</h2></div><button class="text-link" data-action="start" data-journey="'+(state.mode==="dark"?"dark":"normal")+'">New Journey</button></div>';
 if(!records.length) html+='<article class="journey-v2-empty"><div>✦</div><span class="eyebrow">THE STORY STARTS HERE</span><h3>Your first Journey is waiting.</h3><p>Choose a Journey and make a moment worth remembering.</p><button class="btn primary" data-action="start" data-journey="'+(state.mode==="dark"?"dark":"normal")+'">Start Together →</button></article>';
 else html+='<div class="journey-v2-list">'+records.map((record,index)=>{const count=Array.isArray(record.steps)?record.steps.length:0;return '<button class="journey-v2-entry" data-action="journey-detail" data-index="'+index+'"><span class="journey-v2-entry-art">'+(record.journeyId==="dark"?"☾":"♥")+'</span><span class="journey-v2-entry-copy"><small>'+formatJourneyDate(record.completedAt)+'</small><b>'+esc(record.title)+'</b><span>'+count+' moments · Completed</span></span><strong>+'+Number(record.xp||0)+' XP</strong><i>›</i></button>'}).join("")+'</div>';
 html+=renderBottomNav("play")+'</section>'; app.innerHTML=html;
}
function renderJourneyDetail(){
 const p=getProgress(),records=Array.isArray(p.journeyHistory)?p.journeyHistory:[],index=Number(state.__selectedJourney),record=Number.isInteger(index)&&index>=0?records[index]:null;
 if(!record){setView("journey");return}
 let html='<section class="journey-detail-v2"><header class="journey-v2-header"><button class="icon-btn" data-action="journey-back" aria-label="Back">←</button><div><span class="eyebrow">COMPLETED</span><h1>JOURNEY</h1></div><span></span></header>';
 html+='<section class="journey-detail-v2-hero"><div class="journey-detail-v2-mark">'+(record.journeyId==="dark"?"☾":"♥")+'</div><span class="eyebrow">'+formatJourneyDate(record.completedAt)+'</span><h2>'+esc(record.title)+'</h2><p>'+esc(record.subtitle||"A moment together.")+'</p><strong>+'+Number(record.xp||0)+' XP</strong></section>';
 html+='<div class="journey-v2-section-head"><div><span class="eyebrow">THE JOURNEY</span><h2>'+((record.steps||[]).length)+' moments</h2></div></div><section class="journey-detail-v2-steps">'+(record.steps||[]).map((step,i)=>'<article><span class="journey-detail-step-no">'+String(i+1).padStart(2,"0")+'</span><span><b>'+esc(step.title)+'</b><small>'+esc(step.kind||"moment")+'</small></span><strong>✓</strong></article>').join("")+'</section>';
 html+='<button class="btn primary full journey-detail-start" data-action="start" data-journey="'+(record.journeyId==="dark"?"dark":"normal")+'">Play This Journey Again →</button>'+renderBottomNav("play")+'</section>'; app.innerHTML=html;
}
function renderProfile(){
 const p=getProgress(),a=achievementList(),d=daysTogether()||127,n1=state.names.p1||"Deon",n2=state.names.p2||"Naya";
 const list=a.slice(0,5).map(x=>'<div class="profile-v2-achievement"><span>'+(x.unlocked?"♥":"○")+'</span><div><b>'+esc(x.title)+'</b><small>'+esc(x.text)+'</small></div><i>›</i></div>').join("");
 app.innerHTML='<section class="profile-v2"><header class="profile-v2-title"><h1>PROFILES</h1><p>You, Me, and Us</p></header><section class="profile-v2-pair"><div><div class="profile-avatar">'+n1.charAt(0).toUpperCase()+'</div><b>'+esc(n1)+'</b><small>He / Him</small></div><span>♥</span><div><div class="profile-avatar">'+n2.charAt(0).toUpperCase()+'</div><b>'+esc(n2)+'</b><small>She / Her</small></div></section><section class="profile-v2-stats"><span><b>'+p.stats.minigamesPlayed+'</b><small>Games Played</small></span><span><b>'+p.stats.memoriesSaved+'</b><small>Memories</small></span><span><b>'+d+'</b><small>Days Together</small></span></section><blockquote>“Different people,<br>same favorite person.” <span>♥</span></blockquote><div class="profile-v2-actions"><button data-action="settings">♧<span><b>Edit Profiles</b><small>Update your information</small></span>›</button><button data-action="settings">♡<span><b>Relationship Settings</b><small>Customize your experience</small></span>›</button><button>♕<span><b>Achievements</b><small>See your journey together</small></span>›</button></div><section class="profile-v2-couple card"><div class="profile-sunset"></div><div class="eyebrow">OUR PROFILE</div><h2>Two individuals, one beautiful story.</h2><p>Together Since <b>'+(state.relationshipSince?formatJourneyDate(state.relationshipSince):"14 Feb 2024")+'</b></p><div class="profile-tags"><span>Quality Time</span><span>Physical Touch</span><span>Words of Affirmation</span></div></section><section class="profile-v2-achievements card"><div class="home-v2-head"><h2>Achievements</h2><button class="text-link">See All</button></div>'+list+'</section>'+renderBottomNav("profile")+'</section>';
}
function getTopicStats(){const x=readContent();const total=TOPIC_MANAGER_KEYS.reduce((n,k)=>n+(ROLE_KEYS.includes(k)?(x[k]||[]).reduce((m,r)=>m+1+(Array.isArray(r.items)?r.items.length:0),0):(x[k]||[]).length),0);return{total,customTotal:0}}
function renderSettings(){const stats=getTopicStats();app.innerHTML='<section class="settings-v1"><div class="topbar"><span></span><div class="brand">SETTINGS</div><span></span></div><section class="settings-v1-hero"><div class="eyebrow">IGNITE</div><h1>Keep it<br>simple.</h1><p>Settings are for app-wide controls. Game and Journey choices live where you use them.</p></section><section class="settings-v1-list"><div class="settings-v1-section-label">TOPICS</div></section><section class="card settings-topics-v1"><div class="eyebrow">TOPIC LIBRARY</div><div class="settings-topic-total"><strong>'+stats.total+'</strong><span>topics available</span></div><p>Manage the active prompt library used across IGNITE. Changes stay on this device until you restore or reset your data.</p><button class="btn primary full" data-action="topics">Manage My Topics</button></section><section class="settings-v1-list"><div class="settings-v1-section-label">DATA & PRIVACY</div></section><section class="card settings-data-v1"><div class="eyebrow">LOCAL DATA</div><h3>Your data stays with you.</h3><p>Back up, restore, or reset the IGNITE data stored on this device.</p><div class="content-actions"><button type="button" class="btn ghost" data-action="data-export">Export Backup</button><button type="button" class="btn ghost" data-action="data-import">Restore Backup</button><button type="button" class="btn danger" data-action="data-reset">Reset All Data</button></div><input id="app-backup-import" type="file" accept=".json,application/json" hidden></section><section class="card settings-scope-v1"><div class="eyebrow">WHERE THINGS LIVE</div><div class="settings-scope-row"><b>Journey Preferences</b><span>Play → Journey Preferences</span></div><div class="settings-scope-row"><b>Mode</b><span>Home → IGNITE Mode</span></div><div class="settings-scope-row"><b>Dynamic Journey</b><span>Play → Tonight’s Journey / Surprise</span></div></section><div class="settings-about"><span>IGNITE</span><small>Version 1.0.0 · Made for two</small></div>'+renderBottomNav("profile")+'</section>'}
const CONTENT_KEY="ignite-active-content-v1";
const TOPIC_MANAGER_KEYS=["normalCards","explicitCards","truth","dare","intimateTruth","intimateDare","kingNormal","kingDark","roleplayNormal","roleplayDark"];
const TOPIC_MANAGER_LABELS={normalCards:"Journey · Normal",explicitCards:"Journey · After Dark",truth:"Journey · Truth",dare:"Journey · Dare",intimateTruth:"Journey · After Dark Truth",intimateDare:"Journey · After Dark Dare",kingNormal:"King & Slave · Normal",kingDark:"King & Slave · After Dark",roleplayNormal:"Roleplay · Normal",roleplayDark:"Roleplay · After Dark"};
const ROLE_KEYS=["roleplayNormal","roleplayDark"];
function emptyContent(){return Object.fromEntries(TOPIC_MANAGER_KEYS.map(k=>[k,[]]))}
function cleanTopicList(v){return Array.isArray(v)?v.filter(x=>typeof x==="string"&&x.trim()).map(x=>x.trim()):[]}
function cleanRole(r){if(!r||typeof r!=="object")return null;return{id:String(r.id||("role-"+Date.now())),emoji:String(r.emoji||"🎭"),name:String(r.name||"Untitled Role").trim(),desc:String(r.desc||"").trim(),items:Array.isArray(r.items)?r.items.filter(x=>x&&typeof x==="object").map(x=>({context:String(x.context||"").trim(),challenge:String(x.challenge||"").trim()})).filter(x=>x.context||x.challenge):[]}}
function defaultManagerContent(){return{normalCards:[...starterNormalCards],explicitCards:[...starterExplicitCards],truth:[...starterTruth],dare:[...starterDare],intimateTruth:[...starterIntimateTruth],intimateDare:[...starterIntimateDare],kingNormal:[...allKingNormalCommands],kingDark:[...allKingDarkCommands],roleplayNormal:allRoleplayNormalRoles.map(cleanRole).filter(Boolean),roleplayDark:allRoleplayDarkRoles.map(cleanRole).filter(Boolean)}}
function readContent(){const defaults=defaultManagerContent(),out=emptyContent();try{const raw=JSON.parse(localStorage.getItem(CONTENT_KEY)||"null");if(raw&&typeof raw==="object"){for(const k of TOPIC_MANAGER_KEYS)out[k]=ROLE_KEYS.includes(k)?(Array.isArray(raw[k])?raw[k].map(cleanRole).filter(Boolean):[]):cleanTopicList(raw[k]);return out}}catch{}return defaults}
function saveContent(x){localStorage.setItem(CONTENT_KEY,JSON.stringify(x))}
function contentStats(x){return Object.fromEntries(TOPIC_MANAGER_KEYS.map(k=>[k,ROLE_KEYS.includes(k)?x[k].reduce((n,r)=>n+1+r.items.length,0):x[k].length]))}
function contentTotal(x){const stats=contentStats(x);return TOPIC_MANAGER_KEYS.reduce((n,k)=>n+stats[k],0)}
function renderTopics(){
 const x=readContent(),active=state.__topicCategory||"normalCards",roles=ROLE_KEYS.includes(active),items=x[active]||[];
 let html='<section class="settings-v1 topics-manager-v1"><div class="topbar"><button class="btn ghost" data-action="settings">←</button><div class="brand">CONTENT MANAGER</div><span></span></div>';
 html+='<section class="settings-v1-hero"><div class="eyebrow">CONTENT MANAGER</div><h1>One library.<br>Every game.</h1><p>'+contentTotal(x)+' active entries across Journey, King & Slave, and Roleplay.</p></section>';
 html+='<div class="topics-library-actions"><button class="btn primary full" data-topic-action="export">Export topics.js</button><button class="btn ghost full" data-topic-action="import-json">Import source JSON</button><input id="topic-source-import" type="file" accept=".json,application/json" hidden></div>';
 html+='<div class="content-category-grid">'+TOPIC_MANAGER_KEYS.map(k=>'<button class="btn '+(k===active?"primary":"ghost")+'" data-topic-category="'+k+'">'+esc(TOPIC_MANAGER_LABELS[k])+' <small>('+contentStats(x)[k]+')</small></button>').join("")+'</div>';
 if(roles){
  html+='<form class="card topics-add-form" id="role-form"><div class="eyebrow">ADD ROLE</div><div class="field"><label>EMOJI</label><input name="emoji" maxlength="8" value="🎭" required></div><div class="field"><label>ROLE NAME</label><input name="name" maxlength="80" placeholder="Role name" required></div><div class="field"><label>DESCRIPTION</label><textarea name="desc" maxlength="240" rows="3" placeholder="Role description"></textarea></div><button class="btn primary full">Add Role</button></form>';
  html+='<section class="card topics-list-v1"><div class="eyebrow">ROLES</div>';
  if(!items.length)html+='<p class="muted topic-empty">No roles yet.</p>';
  items.forEach((r,i)=>{html+='<details class="topic-group-v1"><summary><b>'+esc(r.emoji)+' '+esc(r.name)+'</b><span>'+r.items.length+' scenes</span></summary><div class="topic-group-items"><p class="muted">'+esc(r.desc)+'</p><form class="role-scene-form" data-role-scene-form="'+i+'"><input name="context" maxlength="300" placeholder="Scene context" required><textarea name="challenge" maxlength="500" rows="2" placeholder="Challenge" required></textarea><button class="btn primary">Add Scene</button></form>';r.items.forEach((it,j)=>{html+='<div class="topic-custom-row"><span><b>'+esc(it.context)+'</b><br>'+esc(it.challenge)+'</span><button class="btn ghost" data-scene-delete="'+i+'" data-scene-index="'+j+'">Delete</button></div>'});html+='<button class="btn danger" data-role-delete="'+i+'">Delete Role</button></div></details>'});
  html+='</section>';
 }else{
  html+='<form class="card topics-add-form" id="topic-form"><div class="eyebrow">ADD CONTENT</div><div class="field"><label>LIBRARY</label><select name="category">'+TOPIC_MANAGER_KEYS.filter(k=>!ROLE_KEYS.includes(k)).map(k=>'<option value="'+k+'" '+(k===active?"selected":"")+'>'+esc(TOPIC_MANAGER_LABELS[k])+'</option>').join("")+'</select></div><div class="field"><label>PROMPT / COMMAND</label><textarea name="text" maxlength="500" rows="4" placeholder="Write a prompt or command..." required></textarea></div><button class="btn primary full">Add Topic</button></form>';
  html+='<section class="card topics-list-v1"><div class="eyebrow">ACTIVE CONTENT</div>';
  if(!items.length)html+='<p class="muted topic-empty">No content here yet.</p>';
  items.forEach((v,i)=>{html+='<div class="topic-custom-row"><span>'+esc(v)+'</span><button class="btn ghost" aria-label="Delete '+esc(v)+'" data-topic-delete="'+active+'" data-topic-index="'+i+'">Delete</button></div>'});
  html+='</section>';
 }
 html+='</section>';app.innerHTML=html;
}
async function exportTopicsJS(){
 const x=readContent(),source=await fetch(new URL("./data/topics.js",import.meta.url)).then(r=>{if(!r.ok)throw new Error("fetch failed");return r.text()}),replacements={allNormalTopics:x.normalCards,allExplicitTopics:x.explicitCards,allTruthTopics:x.truth,allDareTopics:x.dare,allIntimateTruthTopics:x.intimateTruth,allIntimateDareTopics:x.intimateDare,allKingNormalCommands:x.kingNormal,allKingDarkCommands:x.kingDark,allRoleplayNormalRoles:x.roleplayNormal,allRoleplayDarkRoles:x.roleplayDark};
 let out=source;for(const[name,value]of Object.entries(replacements)){const re=new RegExp("export const "+name+"\\s*=\\s*[\\s\\S]*?(?=\
export const |$)");if(!re.test(out))throw new Error("Missing export: "+name);out=out.replace(re,"export const "+name+"="+JSON.stringify(value,null,2)+";")}
 const blob=new Blob([out],{type:"text/javascript;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="topics.js";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);
}
function importContentSource(data){
 const tc=data.totCategories||[],grouped=(items)=>{const map=new Map();for(const it of items||[]){const name=String(it.roleName||"Untitled Role").trim();if(!map.has(name))map.set(name,{id:"custom-"+name.toLowerCase().replace(/[^a-z0-9]+/g,"-"),emoji:String(it.roleEmoji||"🎭"),name,desc:String(it.roleDescription||""),items:[]});map.get(name).items.push({context:String(it.context||""),challenge:String(it.challenge||"")})}return [...map.values()]};
 const afterDark=tc.find(x=>x.name==="After Dark")?.topics||[];
 const x={normalCards:data.categories?.[0]?.topics||[],explicitCards:(data.explicitCategories||[]).flatMap(x=>x.topics||[]),truth:tc.find(x=>x.name==="Truth")?.topics||[],dare:tc.find(x=>x.name==="Dare")?.topics||[],intimateTruth:Array.isArray(data.intimateTruth)?data.intimateTruth.slice():[],intimateDare:Array.isArray(data.intimateDare)?data.intimateDare.slice():[],kingNormal:Array.isArray(data.ksCommands)?data.ksCommands.slice():[],kingDark:Array.isArray(data.ksCommandsExplicit)?data.ksCommandsExplicit.slice():[],roleplayNormal:[...(data.roleplayBuiltInRoles||[]),...grouped(data.roleplayCustomItems)],roleplayDark:[...(data.roleplayBuiltInRolesExplicit||[]),...grouped(data.roleplayCustomItemsExplicit)]};
 saveContent(x);renderTopics();
}
function resetJourneyMechanics(id,journey=null){const j=journey||journeys[id];if(!j)return;for(let i=0;i<j.steps.length;i++)if(j.steps[i].mechanic&&j.steps[i].mechanic!=="roleplay")resetMechanic(j.steps[i].mechanic,i)}
function setMode(mode){state.mode=mode==="dark"?"dark":"normal";save();app.dataset.igniteMode=state.mode;renderHome()}
function generateJourney(id,targetSteps,bias={}){const base=journeys[id==="dark"?"dark":"normal"];const target=Math.max(3,Math.min(12,Number(targetSteps)||5));const closing=base.steps[base.steps.length-1];const opening=base.steps[0];const pool=base.steps.slice(1,-1);const weights=bias.weights||{};const weightFor=s=>{if(s.mechanic==="card"||s.mechanic==="explicit-card")return weights.Talk||1;if(s.mechanic==="rps")return weights.RPS||1;if(s.mechanic==="tod"||s.mechanic==="intimate-tod")return weights.TruthDare||1;if(s.title==="Roleplay")return weights.Roleplay||1;return 1};const chosen=[];let availablePool=pool.slice();while(chosen.length<target-2){if(!availablePool.length)availablePool=pool.slice();let candidates=availablePool.filter(s=>!chosen.length||s.mechanic!==chosen[chosen.length-1].mechanic);if(!candidates.length)candidates=availablePool.slice();const weighted=[];for(const s of candidates){const n=Math.max(1,Math.round(weightFor(s)));for(let i=0;i<n;i++)weighted.push(s)}const picked=weighted[Math.floor(Math.random()*weighted.length)]||candidates[0];chosen.push(picked);const index=availablePool.indexOf(picked);if(index>=0)availablePool.splice(index,1);}return{...JSON.parse(JSON.stringify(base)),steps:[JSON.parse(JSON.stringify(opening)),...chosen.map(s=>JSON.parse(JSON.stringify(s))),JSON.parse(JSON.stringify(closing))]}}
function startJourney(id,options={}){const selected=id==="dark"?"dark":(id==="normal"?"normal":(state.mode==="dark"?"dark":"normal"));const preferred=getPreferences().steps;const target=Math.max(3,Math.min(12,Number(options.targetSteps)||Number(preferred)||5));const bias=options.bias||{};if(state.currentJourney?.id===selected)resetJourneyMechanics(selected,state.currentJourney);delete state.__journeyRoleplayOpen;delete state.__journeyRoleplayDone;state.__journeyTargetSteps=target;state.view="generating";save();render();window.setTimeout(()=>{state.currentJourney=generateJourney(selected,target,bias);resetJourneyMechanics(selected,state.currentJourney);state.step=0;delete state.__journeyTargetSteps;delete state.__journeyRoleplayOpen;delete state.__journeyRoleplayDone;progressionStartJourney(selected);if(!state.names.p1.trim()||!state.names.p2.trim())setView("names");else setView("intro")},650)}
function begin(){const consent=document.querySelector("#consent");if(state.currentJourney.id==="dark"&&(!consent||!consent.checked))return;setView("session")}
function next(award=true){const current=state.currentJourney.steps[state.step];if(award&&current.kind==="ritual")completeRitual(state.currentJourney.id,state.step);else if(award&&current.kind==="activity")completeActivity(state.currentJourney.id,state.step);if(state.step>=state.currentJourney.steps.length-1){completeJourney(state.currentJourney.id,{title:state.currentJourney.title,subtitle:state.currentJourney.subtitle,steps:state.currentJourney.steps});state.view="complete";save();render();return}state.step++;delete state.__journeyRoleplayOpen;delete state.__journeyRoleplayDone;state.__minigameActive=null;save();render()}
function skip(){next(false)}
function exitSession(){delete state.__journeyRoleplayOpen;delete state.__journeyRoleplayDone;state.__minigameActive=null;save();setView("home")}
function restart(){const current=state.currentJourney;if(!current){setView("home");return}const id=current.id;resetJourneyMechanics(id,current);state.currentJourney=JSON.parse(JSON.stringify(current));state.step=0;delete state.__journeyRoleplayOpen;delete state.__journeyRoleplayDone;state.__minigameActive=null;setView("intro")}
function saveNames(form){const d=new FormData(form);state.names.p1=String(d.get("p1")||"").trim();state.names.p2=String(d.get("p2")||"").trim();state.names.couple="";state.relationship=String(d.get("relationship")||"Couple");if(!state.relationshipSince)state.relationshipSince=new Date().toISOString();save();if(state.currentJourney)setView("intro");else setView("home")}
app.addEventListener("input",function(e){if(!e.target?.matches("input[name=steps]"))return;const value=Math.max(3,Math.min(12,Number(e.target.value)||5));e.target.value=String(value);e.target.setAttribute("aria-valuenow",String(value));e.target.setAttribute("aria-valuetext",value+" steps");const out=document.querySelector("#journey-steps-value");if(out)out.textContent=String(value)});
app.addEventListener("change",function(e){if(e.target?.id==="topic-source-import"){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{importContentSource(JSON.parse(reader.result))}catch{alert("Invalid source JSON.")}};reader.readAsText(file);return}if(e.target?.id==="app-backup-import"){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{restoreAppBackup(JSON.parse(reader.result))}catch(err){alert(err?.message||"Invalid IGNITE backup.")}};reader.readAsText(file)}});
app.addEventListener("click",function(e){const settingsLink=e.target.closest(".profile-v1 .topbar [data-action=\"settings\"]");if(settingsLink){setView("settings");return}const ending=e.target.closest("[data-ending]");if(ending){recordInteraction("session-ending",ending.dataset.ending);e.target.closest(".ending-vibes")?.querySelectorAll("button").forEach(b=>b.classList.remove("primary"));ending.classList.add("primary");return}const el=e.target.closest("[data-action]");if(!el)return;const a=el.dataset.action;if(a==="enter"){sessionStorage.setItem("ignite-welcome-seen","1");if(state.names.p1.trim()&&state.names.p2.trim()){state.view="home";save();render();}else{state.view="names";save();render();}}else if(a==="home")setView("home");else if(a==="settings")setView("settings");else if(a==="mode")setMode(el.dataset.mode);else if(a==="profile")setView("profile");else if(a==="memories")setView("memories");else if(a==="memory-capture")setView("memory-capture");else if(a==="bond")setView("bond");else if(a==="preferences")setView("preferences");else if(a==="topics")setView("topics");else if(a==="dynamic"){const ctx=dynamicContext(getLevelInfo(getProgress().xp).level);startJourney(ctx.journeyId,{targetSteps:ctx.targetSteps,bias:ctx.bias});}else if(a==="save-memory"){saveMemory({journey:state.currentJourney?.title||"Journey",xp:getProgress().xp,moment:"A moment together"});setView("home");}else if(a==="minigames"){state.__minigameActive=null;setView("minigames")}else if(a==="minigames-menu"){state.__minigameActive=null;render()}else if(a==="journey")setView("journey");else if(a==="journey-detail"){state.__selectedJourney=Number(el.dataset.index);setView("journey-detail")}else if(a==="journey-back"){state.__selectedJourney=null;setView("journey")}else if(a==="start")startJourney(el.dataset.journey);else if(a==="surprise"){const ctx=surpriseContext(getLevelInfo(getProgress().xp).level);startJourney(ctx.journeyId,{targetSteps:ctx.targetSteps,bias:ctx.bias});}else if(a==="continue")setView("session");else if(a==="begin")begin();else if(a==="next")next();else if(a==="skip")skip();else if(a==="exit")exitSession();else if(a==="again")restart();else if(a==="data-export")exportAppBackup();else if(a==="data-import")document.querySelector("#app-backup-import")?.click();else if(a==="data-reset")resetAllAppData()});
app.addEventListener("click",function(e){const el=e.target.closest("[data-mechanic]");if(!el)return;const s=state.currentJourney&&state.currentJourney.steps[state.step];if(!s||!s.mechanic)return;const a=el.dataset.mechanic;if(s.mechanic==="roleplay"){if(a==="open-roleplay"){state.__minigameActive="roleplay";state.__journeyRoleplayOpen=true;state.__journeyRoleplayDone=false;openMinigame("roleplay",state.mode);recordMinigamePlayed("Roleplay");render();return}if(a==="finish-roleplay"){state.__journeyRoleplayDone=true;state.__journeyRoleplayOpen=false;state.__minigameActive=null;render();return}return}if(a==="guess"||a==="pick")mechanicAction(s.mechanic,state.step,a,el.dataset.value);else if(a==="next-round"||a==="rps-next")mechanicAction(s.mechanic,state.step,"next");else if(a==="draw-card"||a==="next-card"){mechanicAction(s.mechanic,state.step,"draw");if(a==="next-card"){recordOneMore();recordInteraction("one-more",state.mode==="dark"?"Intimate":"Romantic")}}else if(a==="tod-mode")mechanicAction(s.mechanic,state.step,"toggle",el.dataset.value);else if(a==="tod-draw"||a==="next-tod")mechanicAction(s.mechanic,state.step,"draw");render()});
app.addEventListener("click",function(e){const filter=e.target.closest("[data-play-filter]");if(filter){state.__playFilter=filter.dataset.playFilter||"all";renderMinigames();return}const mood=e.target.closest("[data-mood]");if(mood){handleMoodClick(mood);renderHome();return}const vibeHome=e.target.closest("[data-vibe-home]");if(vibeHome){handleVibeClick({dataset:{vibe:vibeHome.dataset.vibeHome}});recordVibe(vibeHome.dataset.vibeHome);renderHome();return}const vibe=e.target.closest("[data-vibe]");if(vibe){handleVibeClick(vibe);recordVibe(vibe.dataset.vibe);renderPreferences();return}const el=e.target.closest("[data-mini-open]");if(!el)return;state.__minigameActive=el.dataset.miniOpen;recordMinigamePlayed(state.__minigameActive);openMinigame(state.__minigameActive,state.mode);render()});
app.addEventListener("click",function(e){const el=e.target.closest("[data-mini]");if(!el)return;const action=el.dataset.mini;const value=action==="chess-square"?el.dataset.index:el.dataset.value;minigameAction(action,value);render();if((action==="snake-roll"||action==="snake-skip")&&state.__minigameActive==="snake")window.__igniteAnimateSnakeMove?.()});
app.addEventListener("click",function(e){
 const b=e.target.closest("[data-bond-action]");
 if(b){const s=readBond(),type=b.dataset.bondType||"daily";if(b.dataset.bondAction==="new"){s[type+"Current"]=pickBond(type,s[type+"Current"]||"");writeBond(s);renderBond()}if(b.dataset.bondAction==="favorite"){const current=s.dailyCurrent||pickBond("daily");if(!s.favorites.includes(current))s.favorites.unshift(current);writeBond(s);renderBond()}return}
 const g=e.target.closest("[data-bond-goal]");if(g){const s=readBond(),i=Number(g.dataset.bondGoal);if(s.goals[i])s.goals[i].done=g.checked;writeBond(s);renderBond()}
});
app.addEventListener("click",function(e){
 const category=e.target.closest("[data-topic-category]");
 if(category){state.__topicCategory=category.dataset.topicCategory;renderTopics();return}
 const topicAction=e.target.closest("[data-topic-action]");
 if(topicAction){if(topicAction.dataset.topicAction==="export"){exportTopicsJS().catch(()=>alert("Export failed."));return}if(topicAction.dataset.topicAction==="import-json"){document.querySelector("#topic-source-import")?.click();return}}
 const del=e.target.closest("[data-topic-delete]");
 if(del){const k=del.dataset.topicDelete,i=Number(del.dataset.topicIndex),x=readContent();if(Number.isInteger(i)&&Array.isArray(x[k])){const value=x[k][i];x[k].splice(i,1);saveContent(x);try{const custom=JSON.parse(localStorage.getItem("ignite-custom-topics-v1")||"null")||{};if(Array.isArray(custom[k])){custom[k]=custom[k].filter(v=>v!==value);localStorage.setItem("ignite-custom-topics-v1",JSON.stringify(custom))}}catch{}}renderTopics();return}
 const roleDel=e.target.closest("[data-role-delete]");
 if(roleDel){const k=state.__topicCategory||"roleplayNormal",i=Number(roleDel.dataset.roleDelete),x=readContent();if(Number.isInteger(i)&&Array.isArray(x[k])){x[k].splice(i,1);saveContent(x)}renderTopics();return}
 const sceneDel=e.target.closest("[data-scene-delete]");
 if(sceneDel){const k=state.__topicCategory||"roleplayNormal",ri=Number(sceneDel.dataset.sceneDelete),si=Number(sceneDel.dataset.sceneIndex),x=readContent();if(x[k]?.[ri]?.items?.[si]){x[k][ri].items.splice(si,1);saveContent(x)}renderTopics();return}
});
app.addEventListener("submit",function(e){if(e.target.matches("#name-form,#settings-form")){e.preventDefault();saveNames(e.target);return}if(e.target.matches("#topic-form")){e.preventDefault();const data=new FormData(e.target),k=String(data.get("category")||"normalCards"),v=String(data.get("text")||"").trim(),x=readContent();if(v&&!x[k].includes(v)){x[k].push(v);saveContent(x);try{const custom=JSON.parse(localStorage.getItem("ignite-custom-topics-v1")||"null")||{};for(const key of TOPIC_MANAGER_KEYS.filter(k=>!ROLE_KEYS.includes(k))){if(!Array.isArray(custom[key]))custom[key]=[]}if(!custom[k].includes(v))custom[k].push(v);localStorage.setItem("ignite-custom-topics-v1",JSON.stringify(custom))}catch{}}renderTopics();return}
if(e.target.matches("#role-form")){e.preventDefault();const data=new FormData(e.target),k=state.__topicCategory||"roleplayNormal",x=readContent();x[k].push(cleanRole({id:"custom-"+Date.now(),emoji:data.get("emoji"),name:data.get("name"),desc:data.get("desc"),items:[]}));saveContent(x);renderTopics();return}
if(e.target.matches("[data-role-scene-form]")){e.preventDefault();const ri=Number(e.target.dataset.roleSceneForm),k=state.__topicCategory||"roleplayNormal",data=new FormData(e.target),x=readContent();if(x[k]?.[ri])x[k][ri].items.push({context:String(data.get("context")||"").trim(),challenge:String(data.get("challenge")||"").trim()});saveContent(x);renderTopics();return}
if(e.target.matches("#preferences-form")){e.preventDefault();handlePreferenceSubmit(e.target);setView("minigames");return}if(e.target.matches("#bond-goal-form")){e.preventDefault();const s=readBond(),goal=String(new FormData(e.target).get("goal")||"").trim();if(goal){s.goals.unshift({text:goal,done:false});writeBond(s)}renderBond();return}if(e.target.matches("#memory-form")){e.preventDefault();const form=e.target,data=new FormData(form),moment=String(data.get("moment")||"A moment together").trim(),note=String(data.get("note")||"").trim(),file=form.querySelector("input[name=photo]")?.files?.[0];const finish=photo=>{saveMemory({journey:state.currentJourney?.title||"Manual Memory",xp:getProgress().xp,moment,note,photo:photo||""});recordMemorySaved();recordInteraction("memory-save");setView("memories")};if(file&&file.size>1024*1024){alert("Photo terlalu besar. Gunakan foto maksimal 1 MB.");return}if(file){const reader=new FileReader();reader.onload=()=>finish(String(reader.result||""));reader.readAsDataURL(file)}else finish("")}});
try{history.scrollRestoration="manual"}catch{};
clearAllTopicStorageOnce();load();if(!sessionStorage.getItem("ignite-welcome-seen")){state.view="welcome"}else if(!state.names.p1.trim()||!state.names.p2.trim()){state.view="names"}else if(state.view==="names"){state.view="home"}initAccessibility(app);render();requestAnimationFrame(resetViewport);