const STORAGE_KEY="ignite-redesign-v3";
const state={names:{p1:"",p2:"",couple:""},currentJourney:null,step:0,view:"home"};

const journeys={
 normal:{id:"normal",title:"Normal Journey",subtitle:"Talk, play, and get a little closer.",mood:"Romantic · Playful · Warm",steps:[
  {kind:"ritual",icon:"✦",title:"Warm Up",text:"Mulai dengan ritual ringan untuk mengubah suasana menjadi waktu kalian berdua.",action:"Begin Ritual"},
  {kind:"activity",icon:"♡",title:"Talk Card",text:"Ambil satu kartu dan beri pasanganmu ruang untuk menjawab dengan jujur.",action:"Reveal Card"},
  {kind:"ritual",icon:"✊",title:"Change the Energy",text:"Mainkan Rock Paper Scissors. Pemenang menentukan siapa yang mulai.",action:"Play Ritual"},
  {kind:"activity",icon:"◇",title:"Truth or Dare",text:"Satu pertanyaan atau satu tantangan. Pilih dengan spontan.",action:"Continue"},
  {kind:"activity",icon:"♡",title:"One More Card",text:"Satu momen terakhir untuk saling mengenal sedikit lebih jauh.",action:"Continue"},
  {kind:"closing",icon:"♥",title:"Close the Journey",text:"Apa satu hal kecil dari pasanganmu yang paling kamu nikmati saat ini?",action:"Finish Journey"}]},
 dark:{id:"dark",title:"After Dark",subtitle:"A more intimate journey for two.",mood:"Intimate · Daring · Tasteful",steps:[
  {kind:"ritual",icon:"✦",title:"Set the Mood",text:"Mulai perlahan. Pastikan kalian berdua nyaman dan siap melanjutkan.",action:"Begin Ritual"},
  {kind:"activity",icon:"🔥",title:"Explicit Card",text:"Masuk ke kartu yang lebih berani setelah kalian berdua setuju.",action:"Reveal Card"},
  {kind:"ritual",icon:"✊",title:"Change the Energy",text:"Gunakan ritual singkat untuk mengubah tempo sebelum aktivitas berikutnya.",action:"Play Ritual"},
  {kind:"activity",icon:"◇",title:"Intimate Truth or Dare",text:"Pilih pertanyaan atau tantangan yang terasa nyaman untuk kalian berdua.",action:"Continue"},
  {kind:"activity",icon:"🎭",title:"Roleplay",text:"Lanjutkan dengan skenario roleplay yang tersedia di IGNITE.",action:"Continue"},
  {kind:"closing",icon:"♥",title:"Close the Journey",text:"Selesai. Tidak perlu mengejar apa pun—cukup nikmati momennya.",action:"Finish Journey"}]}
};

const app=document.querySelector("#app");
function load(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(saved)Object.assign(state,saved)}catch{}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function coupleName(){const c=state.names.couple&&state.names.couple.trim();return c||((state.names.p1&&state.names.p1.trim())||"Player 1")+" & "+((state.names.p2&&state.names.p2.trim())||"Player 2")}
function esc(v){return String(v).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]})}
function setView(view){state.view=view;save();render()}
function render(){if(state.view==="home")renderHome();else if(state.view==="names")renderNames();else if(state.view==="intro")renderIntro();else if(state.view==="session")renderSession();else if(state.view==="complete")renderComplete();else if(state.view==="minigames")renderMinigames();else if(state.view==="settings")renderSettings()}

function renderHome(){
 let html='<div class="topbar"><div class="brand">IGNITE</div><button class="profile-chip" data-action="settings">'+esc(coupleName())+'</button></div>';
 html+='<section class="hero"><div class="eyebrow">Couple Experience</div><h1>Let’s spend<br>some time<br>together.</h1><p>IGNITE membantu kalian menjalani satu pengalaman bersama, bukan sekadar memilih game.</p></section>';
 if(state.currentJourney){const pct=Math.round((state.step/(state.currentJourney.steps.length-1))*100);html+='<div class="section-label">Continue</div><button class="card continue-card" data-action="continue"><div class="continue-copy"><strong>'+esc(state.currentJourney.title)+'</strong><span class="muted">Moment '+(state.step+1)+' of '+state.currentJourney.steps.length+'</span><div class="progress"><span style="width:'+pct+'%"></span></div></div><span>→</span></button>'}
 html+='<div class="section-label">Start a Journey</div><div class="experience-grid">';
 html+='<button class="card experience-card normal" data-action="start" data-journey="normal"><div class="icon">💕</div><h3>Normal</h3><p>Talk, play, connect. A warm experience for any date.</p></button>';
 html+='<button class="card experience-card dark" data-action="start" data-journey="dark"><div class="icon">🔥</div><h3>After Dark</h3><p>More intimate, more daring, always mutual. 18+.</p></button></div>';
 html+='<div class="section-label">Direct Play</div><div class="mini-grid"><button class="card mini-card" data-action="minigames"><span>🎮</span><strong>Minigames</strong><span>Roleplay, Chess, Snake &amp; Ladder, King &amp; Slave.</span></button><button class="card mini-card" data-action="settings"><span>⚙</span><strong>Settings</strong><span>Couple identity and app preferences.</span></button></div>';
 app.innerHTML=html;
}
function renderNames(){app.innerHTML='<div class="topbar"><button class="btn ghost" data-action="home">←</button><div class="brand">COUPLE</div><span></span></div><div class="hero"><div class="eyebrow">Before Your Journey</div><h2>Who is here?</h2><p>Nama akan digunakan secara natural selama kalian bermain.</p></div><form class="card name-form" id="name-form"><div class="field"><label>Player 1</label><input name="p1" maxlength="30" value="'+esc(state.names.p1)+'" placeholder="Nama kamu" required></div><div class="field"><label>Player 2</label><input name="p2" maxlength="30" value="'+esc(state.names.p2)+'" placeholder="Nama pasangan" required></div><div class="field"><label>Couple name <span class="muted">(optional)</span></label><input name="couple" maxlength="40" value="'+esc(state.names.couple)+'" placeholder="Contoh: Deon &amp; Ara"></div><button class="btn primary full">Save Couple</button></form>'}
function renderIntro(){const j=state.currentJourney;if(!j){state.view="home";return renderHome()}const dark=j.id==="dark";let html='<section class="intro-shell"><div class="topbar"><button class="btn ghost" data-action="home">←</button><div class="brand">IGNITE</div><span></span></div><article class="card intro-card"><div class="mark">'+(dark?"🔥":"✦")+'</div><div class="meta-pill">'+esc(j.mood)+'</div><h2>'+esc(j.title)+'</h2><p>'+esc(j.subtitle)+'<br><br>IGNITE akan menentukan ritmenya. Kalian menentukan kapan lanjut.</p>';if(dark)html+='<label class="consent"><input id="consent" type="checkbox"> <span>Kami berdua berusia 18+ dan setuju untuk melanjutkan. Kami tahu kami bisa berhenti kapan saja.</span></label>';html+='<button class="btn primary full" data-action="begin">'+(dark?"Enter After Dark":"Begin Journey")+' →</button></article></section>';app.innerHTML=html}
function renderSession(){const j=state.currentJourney;if(!j){state.view="home";return renderHome()}const s=j.steps[state.step],progress=Math.round((state.step/(j.steps.length-1))*100);app.innerHTML='<section class="session"><div class="session-head"><button class="btn ghost" data-action="exit">Exit</button><div class="session-count">'+(state.step+1)+' / '+j.steps.length+'</div></div><div class="progress"><span style="width:'+progress+'%"></span></div><article class="card session-card"><div class="ritual-mark">'+s.icon+'</div><div class="type">'+esc(s.kind)+'</div><h2>'+esc(s.title)+'</h2><p>'+esc(s.text)+'</p><div class="session-actions btn-row"><button class="btn ghost" data-action="skip">Skip</button><button class="btn primary" data-action="next">'+esc(s.action)+' →</button></div></article><div class="session-footer">'+esc(coupleName())+'</div></section>'}
function renderComplete(){app.innerHTML='<section class="complete-shell"><article class="card complete-card"><div class="mark">♥</div><div class="eyebrow">Journey Complete</div><h2>That was your time.</h2><p>Terima kasih sudah meluangkan waktu untuk satu sama lain.</p><div class="btn-row"><button class="btn ghost" data-action="home">Back to Journey</button><button class="btn primary" data-action="again">Again →</button></div></article></section>'}
function renderMinigames(){app.innerHTML='<div class="topbar"><button class="btn ghost" data-action="home">←</button><div class="brand">MINIGAMES</div><span></span></div><div class="hero"><div class="eyebrow">Play Directly</div><h2>Choose a game.</h2><p>Kalau kalian tahu game yang ingin dimainkan, langsung masuk ke sini. Tidak perlu memulai Journey.</p></div><div class="mini-grid"><button class="card mini-card"><span>🎭</span><strong>Roleplay</strong><span>Existing roleplay system.</span></button><button class="card mini-card"><span>👑</span><strong>King &amp; Slave</strong><span>Existing command system.</span></button><button class="card mini-card"><span>♟</span><strong>Chess</strong><span>Existing chess system.</span></button><button class="card mini-card"><span>🐍</span><strong>Snake &amp; Ladder</strong><span>Existing board game.</span></button></div><p class="note">Direct-play mechanics akan dihubungkan dari legacy pada Phase 3. Untuk sekarang, struktur navigasinya sudah dipisahkan.</p>'}
function renderSettings(){app.innerHTML='<div class="topbar"><button class="btn ghost" data-action="home">←</button><div class="brand">SETTINGS</div><span></span></div><div class="hero"><div class="eyebrow">Couple Profile</div><h2>Make it yours.</h2><p>Untuk MVP, Settings menjaga identitas pasangan tetap sederhana. Management konten legacy akan dimigrasikan setelah Journey stabil.</p></div><form class="card name-form" id="settings-form"><div class="field"><label>Player 1</label><input name="p1" maxlength="30" value="'+esc(state.names.p1)+'" required></div><div class="field"><label>Player 2</label><input name="p2" maxlength="30" value="'+esc(state.names.p2)+'" required></div><div class="field"><label>Couple name <span class="muted">(optional)</span></label><input name="couple" maxlength="40" value="'+esc(state.names.couple)+'"></div><button class="btn primary full">Save Changes</button></form>'}

function startJourney(id){state.currentJourney=JSON.parse(JSON.stringify(journeys[id]));state.step=0;if(!state.names.p1?.trim()||!state.names.p2?.trim())setView("names");else setView("intro")}
function begin(){if(state.currentJourney?.id==="dark"&&!document.querySelector("#consent")?.checked)return;setView("session")}
function next(){if(state.step>=state.currentJourney.steps.length-1){state.view="complete";save();return}state.step++;save();renderSession()}
function skip(){next()}
function exitSession(){save();setView("home")}
function restart(){const id=state.currentJourney?.id;state.currentJourney=id?JSON.parse(JSON.stringify(journeys[id])):null;state.step=0;setView("intro")}
function saveNames(form){const d=new FormData(form);state.names.p1=String(d.get("p1")||"").trim();state.names.p2=String(d.get("p2")||"").trim();state.names.couple=String(d.get("couple")||"").trim();save();if(state.currentJourney)setView("intro");else setView("home")}

app.addEventListener("click",e=>{const el=e.target.closest("[data-action]");if(!el)return;const a=el.dataset.action;if(a==="home")setView("home");if(a==="settings")setView("settings");if(a==="names")setView("names");if(a==="minigames")setView("minigames");if(a==="start")startJourney(el.dataset.journey);if(a==="continue")setView("session");if(a==="begin")begin();if(a==="next")next();if(a==="skip")skip();if(a==="exit")exitSession();if(a==="again")restart()});
app.addEventListener("submit",e=>{if(!e.target.matches("#name-form,#settings-form"))return;e.preventDefault();saveNames(e.target)});
load();render();
