const BACK="rnbqkbnr";
function initBoard(){const b=Array(64).fill(null);for(let i=0;i<8;i++){b[i]={c:"b",t:BACK[i]};b[8+i]={c:"b",t:"p"};b[48+i]={c:"w",t:"p"};b[56+i]={c:"w",t:BACK[i]}}return b}
function xy(i){return[Math.floor(i/8),i%8]}function idx(r,f){return r>=0&&r<8&&f>=0&&f<8?r*8+f:-1}
function pseudo(b,from,attack=false){const p=b[from],a=[],[r,f]=xy(from);if(!p)return a;const add=(rr,ff)=>{const i=idx(rr,ff);if(i<0)return false;if(!b[i]){a.push(i);return true}if(b[i].c!==p.c)a.push(i);return false};if(p.t==="p"){const d=p.c==="w"?-1:1;if(attack)[-1,1].forEach(x=>{const i=idx(r+d,f+x);if(i>=0)a.push(i)});else{const i=idx(r+d,f);if(i>=0&&!b[i]){a.push(i);const j=idx(r+2*d,f);if((p.c==="w"?r===6:r===1)&&!b[j])a.push(j)}[-1,1].forEach(x=>{const j=idx(r+d,f+x);if(j>=0&&b[j]&&b[j].c!==p.c)a.push(j)})}}else if(p.t==="n")[[2,1],[2,-1],[-2,1],[-2,-1],[1,2],[1,-2],[-1,2],[-1,-2]].forEach(x=>add(r+x[0],f+x[1]));else{const ds=p.t==="b" ? [[1,1],[1,-1],[-1,1],[-1,-1]] : p.t==="r" ? [[1,0],[-1,0],[0,1],[0,-1]] : [[1,1],[1,-1],[-1,1],[-1,-1],[1,0],[-1,0],[0,1],[0,-1]];if(p.t==="k")ds.forEach(d=>add(r+d[0],f+d[1]));else ds.forEach(d=>{let rr=r+d[0],ff=f+d[1];while(add(rr,ff)){rr+=d[0];ff+=d[1]}})}return a}
function attacked(b,s,col){for(let i=0;i<64;i++)if(b[i]&&b[i].c===col&&pseudo(b,i,true).includes(s))return true;return false}
function inCheck(b,col){const k=b.findIndex(p=>p&&p.c===col&&p.t==="k");return k<0||attacked(b,k,col==="w"?"b":"w")}
function legal(b,f,t){const p=b[f];if(!p||p.c!==b.turn||b[t]&&b[t].t==="k"||!pseudo(b,f).includes(t))return false;const n=b.map(x=>x&&{...x});n[t]=n[f];n[f]=null;return !inCheck(n,p.c)}
function moves(b,f){return pseudo(b,f).filter(t=>legal(b,f,t))}
const PIECE={p:"♟",r:"♜",n:"♞",b:"♝",q:"♛",k:"♚"};
export function createChessState(){return{board:initBoard(),turn:"w",selected:null,over:false,history:[]}}
export function chessClick(s,i){if(s.over)return;if(s.selected===null){if(s.board[i]&&s.board[i].c===s.turn)s.selected=i}else if(legal(s.board,s.selected,i)){const f=s.selected,p=s.board[f],cap=s.board[i];s.history.push(JSON.stringify({board:s.board,turn:s.turn}));s.board[i]=p;s.board[f]=null;if(p.t==="p"&&Math.floor(i/8)===(p.c==="w"?0:7))p.t="q";s.turn=s.turn==="w"?"b":"w";s.selected=null;if(cap){};let any=false;for(let x=0;x<64;x++)if(s.board[x]&&s.board[x].c===s.turn&&moves(s.board,x).length){any=true;break}if(!any)s.over=true}else{s.selected=s.board[i]&&s.board[i].c===s.turn?i:null}}
export function chessUndo(s){if(!s.history.length)return;const x=JSON.parse(s.history.pop());s.board=x.board;s.turn=x.turn;s.selected=null;s.over=false}
export function renderChess(s,names){let board='<div class="chess-board">'+s.board.map((p,i)=>'<button class="chess-square '+(((Math.floor(i/8)+i)%2)?"dark":"light")+(s.selected===i?" selected":"")+(s.selected!==null&&moves(s.board,s.selected).includes(i)?" legal":"")+'" data-mini="chess-square" data-index="'+i+'">'+(p?PIECE[p.t]:"")+'</button>').join("")+'</div>';const turn=s.over?"Game selesai":(s.turn==="w"?names[0]:names[1])+" bergerak";return '<div class="game-active"><div class="game-meta">♟ Chess · '+escapeHtml(turn)+'</div>'+board+'<div class="btn-row"><button class="btn ghost" data-mini="chess-undo">Undo</button><button class="btn primary" data-mini="chess-reset">Restart</button></div></div>'}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
