import {getMemories,getMemoryStats} from "./memories.js?v=20260928-02";
import {getPreferences,savePreferences,VIBES} from "./preferences.js?v=20260928-02";
import {getUnlocks} from "./unlocks.js?v=20260928-02";
import {createSurpriseContext} from "./surprise.js?v=20260928-02";
import {buildJourney} from "./dynamicJourney.js?v=20260928-02";
import {getAdaptive} from "./adaptive.js?v=20260928-02";
import {getProgress,achievementList} from "../progression.js?v=20260928-02";
import {buildContext,getMoodMeta,MOODS,setMood} from "./context.js?v=20260928-02";
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
export function getCurrentContext(level){return buildContext({level,preferences:getPreferences(),memories:getMemories()})}
function formatTime(hour,minute){return String(hour).padStart(2,"0")+":"+String(minute).padStart(2,"0")}
export function renderContextSummary(level){
 const ctx=getCurrentContext(level),mood=ctx.mood,time=ctx.time;
 return '<section class="card context-card"><div class="eyebrow">Right now</div><div class="context-main"><div><strong>'+esc(time.periodLabel)+'</strong><span>'+formatTime(time.hour,time.minute)+(time.isWeekend?" · Weekend":" · Weekday")+'</span></div><div class="context-mood"><strong>'+(mood?esc(mood.label):"No mood")+'</strong><span>'+(mood?"Current mood":"Set a mood for better Journey suggestions")+'</span></div></div><div class="mood-picker" aria-label="Current mood">'+MOODS.map(m=>'<button type="button" class="btn choice '+(mood?.id===m.id?"primary":"ghost")+'" data-mood="'+m.id+'" aria-pressed="'+(mood?.id===m.id?"true":"false")+'">'+m.icon+" "+esc(m.label)+'</button>').join("")+'</div></section>';
}
export function handleMoodClick(button){setMood(button.dataset.mood);return getMoodMeta(button.dataset.mood)}
export function renderMemorySummary(){const s=getMemoryStats(),m=s.latest,a=getAdaptive(),top=Object.entries(a.vibes||{}).sort((x,y)=>y[1]-x[1]).filter(x=>x[1]>0).slice(0,2).map(x=>x[0]).join(" · ");return '<section class="card memory-summary"><div class="eyebrow">Your Moments</div><div class="memory-summary-row"><div><strong>'+s.count+'</strong><span>saved moments</span></div><div><strong>'+s.streak+'</strong><span>day streak</span></div></div><p class="muted">'+(m?esc(m.moment):"Simpan momen pertama kalian setelah Journey.")+'</p>'+(top?'<div class="adaptive-note"><span>IGNITE is learning your vibe</span><strong>'+esc(top)+'</strong></div>':"")+'<button class="btn ghost full" data-action="memories">Open Memories</button></section>'}
export function renderMemories(bottomNav){
 const all=getMemories(),stats=getMemoryStats(),p=getProgress(),ach=achievementList();
 const sorted=filtered.slice().sort((a,b)=>new Date(b.date)-new Date(a.date));
 const cards=sorted.slice(0,8).map(m=>'<article class="memory-v2-card"><div class="memory-v2-thumb">'+(m.photo?'<img src="'+esc(m.photo)+'" alt="">':'♥')+'</div><div><b>'+esc(m.moment||m.journey||"Special moment")+'</b><small>'+new Date(m.date||Date.now()).toLocaleDateString("id-ID")+'</small>'+(m.location?'<small>⌖ '+esc(m.location)+'</small>':"")+'</div><span class="memory-v2-heart">♥</span></article>').join("");
 return '<section class="memories-v2"><header class="memories-v2-title"><h1>MEMORIES</h1><p>OUR SPECIAL MOMENTS</p><button class="icon-btn" data-action="memory-capture">+</button></header><section class="memories-v2-hero"><div class="memory-box">♥</div><h2>Every moment<br>has a story.</h2><p>Simpan tempat spesial, foto, cerita, dan<br>momen berharga kalian di sini.</p><button class="btn primary" data-action="memory-capture">＋ Add Memory</button></section><section class="memories-v2-categories"><div class="home-v2-head"><h2>Memory Categories</h2></div><div class="category-grid"><button type="button" data-memory-filter="all" class="'+(filter==="all"?"active":"")+'"><b>▦</b><span>All</span><small>'+all.length+' Moments</small></button><button type="button" data-memory-filter="places" class="'+(filter==="places"?"active":"")+'"><b>⌖</b><span>Places</span><small>'+all.filter(x=>x.location).length+'</small></button><button type="button" data-memory-filter="dates" class="'+(filter==="dates"?"active":"")+'"><b>▣</b><span>Dates</span><small>'+all.filter(x=>x.date).length+'</small></button><button type="button" data-memory-filter="notes" class="'+(filter==="notes"?"active":"")+'"><b>▤</b><span>Notes</span><small>'+all.filter(x=>x.note).length+'</small></button></div></section><section class="memories-v2-list"><div class="home-v2-head"><h2>Recent Memories</h2><button class="text-link" type="button" data-memory-filter="all">See All</button></div><div class="memory-v2-grid">'+(cards||'<div class="memory-v2-empty"><span>♥</span><h3>No memories yet</h3><p>Save your first special moment.</p></div>')+'</div></section><section class="memory-v2-insight card"><span class="eyebrow">YOUR STORY</span><b>'+ach.filter(x=>x.unlocked).length+' milestones unlocked</b><small>Level '+p.level+' · '+esc(p.title)+' · best streak '+Math.max(stats.streak,Number(p.stats.longestStreak)||0)+' days</small></section>'+bottomNav+'</section>';
}
export function renderPreferences(){const p=getPreferences();const selected=p.vibes[0]||VIBES[0];return '<div class="topbar"><button class="btn ghost" data-action="minigames">←</button><div class="brand">PREFERENCES</div><span></span></div><div class="hero"><div class="eyebrow">Journey Preferences</div><h2>How do you want to connect?</h2><p>Pilih vibe dan tentukan sendiri berapa banyak step yang ingin kalian jalani.</p></div><form class="card preference-form" id="preferences-form"><div class="field"><label>Vibe</label><div class="choice-grid preference-grid">'+VIBES.map(v=>'<button type="button" class="btn choice '+(selected===v?"primary":"ghost")+'" data-vibe="'+esc(v)+'" aria-pressed="'+(selected===v?"true":"false")+'">'+esc(v)+'</button>').join("")+'</div></div><div class="field"><label>Journey Steps</label><p class="muted">Berapa banyak tahap yang ingin kalian jalani?</p><div class="journey-steps-control"><div class="journey-steps-value" aria-live="polite"><strong id="journey-steps-value">'+p.steps+'</strong><span>steps</span></div><input class="journey-steps-slider" type="range" name="steps" min="3" max="12" step="1" value="'+p.steps+'" aria-label="Journey Steps" aria-valuemin="3" aria-valuemax="12" aria-valuenow="'+p.steps+'" aria-valuetext="'+p.steps+' steps"><div class="journey-steps-scale" aria-hidden="true"><span>3</span><span>6</span><span>9</span><span>12</span></div></div></div><button class="btn primary full">Save Preferences</button></form>'}
export function renderFeatureSettings(level,bottomNav){const p=getPreferences();return '<section class="card feature-settings"><div class="eyebrow">Personalization</div><h3>Make the next Journey yours.</h3><p class="muted">Vibe dan jumlah step memengaruhi Dynamic Journey dan Surprise Mode.</p><div class="settings-links"><button class="btn ghost full" data-action="preferences">Journey Preferences</button><button class="btn ghost full" data-action="dynamic">Build Dynamic Journey</button><button class="btn ghost full" data-action="memories">Couple Memories</button><div class="unlock-summary"><div class="eyebrow">Unlocked at Level '+level+'</div><p>'+esc(getUnlocks(level).join(" · "))+'</p></div></div></section>'+bottomNav}
export function handleVibeClick(button){const p=getPreferences(),v=button.dataset.vibe;if(!VIBES.includes(v))return false;savePreferences({...p,vibes:[v]});return true}
export function handlePreferenceSubmit(form){const d=new FormData(form);const p=getPreferences();savePreferences({...p,steps:Number(d.get("steps")||5)});return true}
export function surpriseContext(level){return createSurpriseContext({level,preferences:getPreferences(),memories:getMemories(),context:getCurrentContext(level)})}
export function dynamicContext(level){return buildJourney({level,preferences:getPreferences(),memories:getMemories(),context:getCurrentContext(level)})}
