import {getMemories,getMemoryStats} from "./memories.js";
import {getPreferences,savePreferences,VIBES} from "./preferences.js";
import {getUnlocks} from "./unlocks.js";
import {createSurpriseContext} from "./surprise.js";
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
export function renderMemorySummary(){const s=getMemoryStats(),m=s.latest;return '<section class="card memory-summary"><div class="eyebrow">Your Moments</div><div class="memory-summary-row"><div><strong>'+s.count+'</strong><span>saved moments</span></div><div><strong>'+s.streak+'</strong><span>day streak</span></div></div><p class="muted">'+(m?esc(m.moment):"Simpan momen pertama kalian setelah Journey.")+'</p><button class="btn ghost full" data-action="memories">Open Memories</button></section>'}
export function renderMemories(bottomNav){const all=getMemories();return '<div class="topbar"><button class="btn ghost" data-action="home">←</button><div class="brand">MEMORIES</div><span></span></div><div class="hero"><div class="eyebrow">Your Moments</div><h2>Keep the moments.</h2><p>Riwayat ini tersimpan lokal di browser kalian.</p></div><section class="card memory-summary"><div class="memory-summary-row"><div><strong>'+all.length+'</strong><span>moments</span></div><div><strong>'+getMemoryStats().streak+'</strong><span>day streak</span></div></div></section><section class="memory-list">'+(all.length?all.map(m=>'<article class="card memory-item"><div class="memory-item-head"><span>'+esc(m.journey)+'</span><time>'+new Date(m.date).toLocaleDateString("id-ID")+'</time></div><h3>'+esc(m.moment)+'</h3>'+(m.note?'<p>'+esc(m.note)+'</p>':"")+(m.photo?'<img src="'+esc(m.photo)+'" alt="Saved moment">':"")+'</article>').join(""):'<article class="card empty-state"><h3>No moments yet.</h3><p>Complete a Journey to save your first memory.</p></article>')+'</section>'+bottomNav}
export function renderPreferences(){const p=getPreferences();return '<div class="topbar"><button class="btn ghost" data-action="settings">←</button><div class="brand">PREFERENCES</div><span></span></div><div class="hero"><div class="eyebrow">Journey Preferences</div><h2>How do you want to connect?</h2><p>Preferensi ini dipakai untuk menyusun Journey berikutnya.</p></div><form class="card preference-form" id="preferences-form"><div class="field"><label>Vibe</label><div class="choice-grid preference-grid">'+VIBES.map(v=>'<button type="button" class="btn choice '+(p.vibes.includes(v)?"primary":"ghost")+'" data-vibe="'+esc(v)+'">'+esc(v)+'</button>').join("")+'</div></div><div class="field"><label>Duration</label><select name="duration"><option value="short" '+(p.duration==="short"?"selected":"")+'>Short</option><option value="medium" '+(p.duration==="medium"?"selected":"")+'>Medium</option><option value="long" '+(p.duration==="long"?"selected":"")+'>Long</option></select></div><div class="field"><label>Intensity</label><select name="intensity"><option value="gentle" '+(p.intensity==="gentle"?"selected":"")+'>Gentle</option><option value="balanced" '+(p.intensity==="balanced"?"selected":"")+'>Balanced</option><option value="bold" '+(p.intensity==="bold"?"selected":"")+'>Bold</option></select></div><button class="btn primary full">Save Preferences</button></form>'}
export function renderFeatureSettings(level,bottomNav){const p=getPreferences();return '<section class="card feature-settings"><div class="eyebrow">Personalization</div><h3>Make the next Journey yours.</h3><p class="muted">Vibe, duration, dan intensity memengaruhi Dynamic Journey dan Surprise Mode.</p><div class="settings-links"><button class="btn ghost full" data-action="preferences">Journey Preferences</button><button class="btn ghost full" data-action="memories">Couple Memories</button><div class="unlock-summary"><div class="eyebrow">Unlocked at Level '+level+'</div><p>'+esc(getUnlocks(level).join(" · "))+'</p></div></div></section>'+bottomNav}
export function handleVibeClick(button){const p=getPreferences(),v=button.dataset.vibe;const vibes=p.vibes.includes(v)?p.vibes.filter(x=>x!==v):[...p.vibes,v];savePreferences({...p,vibes:vibes.length?vibes:["Romantic"]});return true}
export function handlePreferenceSubmit(form){const d=new FormData(form);const p=getPreferences();savePreferences({...p,duration:String(d.get("duration")||"medium"),intensity:String(d.get("intensity")||"balanced")});return true}
export function surpriseContext(level){return createSurpriseContext({level,preferences:getPreferences(),memories:getMemories()})}
